import { modules0to2 } from "./modules-0-2";
import { modules3to5 } from "./modules-3-5";
import { modules6to8 } from "./modules-6-8";
import { modules9 } from "./modules-9";
import { modules10 } from "./modules-10";
import type { GlossaryEntry, Lesson } from "./model";
import { validateCurriculum } from "./validate";

export const curriculum = [
  ...modules0to2,
  ...modules3to5,
  ...modules6to8,
  ...modules9,
  ...modules10,
];

const issues = validateCurriculum(curriculum);
if (issues.length > 0) {
  throw new Error(
    `Invalid curriculum:\n${issues.map((issue) => `${issue.path}: ${issue.message}`).join("\n")}`,
  );
}

export const lessons: Lesson[] = curriculum
  .flatMap((module) => module.lessons)
  .sort((left, right) => left.module - right.module || left.order - right.order);

export const lessonById = new Map(lessons.map((lesson) => [lesson.id, lesson]));

const definitions: Record<string, string> = {
  "evidence binding": "A canonical identity join between a claim and the exact source, model, artifact, target, and observation that support it.",
  refinement: "A proof or validated relation showing that one representation preserves another representation's specified behavior.",
  authority: "An unforgeable capability to perform or approve an operation, distinct from descriptive evidence.",
  gfx942: "The AMD CDNA 3 processor target used by MI300X; feature modifiers such as xnack remain part of the target identity.",
  HSACO: "An AMD HSA code object containing executable kernels, descriptors, metadata, and ELF identity.",
  "target ID": "A processor plus normalized target features; parsed target text is not hardware attestation.",
  "code object": "A loadable GPU binary and its ABI/resource metadata.",
  ThreadIndex: "A logical invocation index witness used to preserve the association between an invocation and its allowed access mapping.",
  DisjointSlice: "A device view whose safe mutable access is partitioned by a matching thread index space.",
  "rounded tail": "Launched lanes beyond the logical element extent, which must perform no access.",
  "write partition": "A mapping that assigns concurrently executing identities disjoint writable regions.",
  "total output coverage": "A proof that every required logical output coordinate has an executed final owner; it does not by itself prove termination or value correctness.",
  finality: "The property that a modeled output effect is the last observable write to its logical coordinate.",
  "typed kernel": "A kernel whose generated host API binds a reviewed signature, ABI, artifact, launch, and ownership profile.",
  Prepared: "A launch state retaining validated arguments and borrows until dispatch completes.",
  "source sharing": "Using one algorithmic body from both executable Rust and its proof harness through explicit adapters.",
  "IEEE refinement": "A relation between abstract arithmetic and exact floating-point formats, operations, rounding, and exceptional values.",
  "numeric contract": "An explicit exact-bit-vector, exact-floating, relaxed, or error-bounded interpretation of arithmetic operations and exceptional behavior.",
  "arithmetic definedness": "The preconditions that rule out checked-overflow traps and invalid division, remainder, shift, cast, indexing, or other partial operations.",
  "CPU semantic simulation": "Bounded deterministic execution of exact verified canonical Kernel IR V7 on a CPU, admitted either directly or from an authority-free .fe2sim exported through the sole production source-to-KIR stages.",
  "simulated observation": "A dynamic result from the CPU semantic simulator. It is neither a hardware observation nor proof that generated machine code is equivalent.",
  "formal memory": "The typed virtual memory boundary that tracks allocation identity, byte extent, alignment, permissions, initialization, and provenance without using raw host pointers.",
  "deterministic schedule": "A stable semantic work-item execution order recorded for reproducibility; it does not claim that GPU hardware uses the same order.",
  requires: "A Verus precondition that the caller must establish.",
  ensures: "A Verus postcondition established when the function or proof returns.",
  "ghost state": "Proof-only state erased from executable code and unable to authenticate runtime facts by itself.",
  "expected-negative test": "An intentionally invalid theorem or program that must fail at a specified obligation.",
  region: "An allocation identity, address space, byte offset, and byte length describing a memory effect.",
  provenance: "The authorized allocation identity behind an address, not merely its numeric pointer value.",
  initialization: "Evidence that a read region contains a value defined by the model.",
  injectivity: "The property that distinct invocation identities map to distinct outputs.",
  "race freedom": "Absence of unordered conflicting accesses to overlapping regions.",
  wave64: "A 64-lane AMD wavefront profile used by the reviewed gfx942 collective contracts.",
  "active mask": "The participating lanes for a wave operation.",
  reduction: "A scoped combination of participating values into one result.",
  "contribution domain": "The declared participants and logical contributions that must occur with the required multiplicity before a reduction-value theorem can apply.",
  scan: "A scoped prefix computation that returns one result per participant.",
  "participation scope": "The exact wave, workgroup, device, or system participants covered by an operation.",
  LDS: "AMD workgroup-local data share memory.",
  epoch: "A memory-effect phase separated by a synchronization boundary.",
  "barrier convergence": "The requirement that all participants reach matching dynamic barrier instances in the same order.",
  "atomic scope": "The set of agents whose atomic ordering is covered.",
  ordering: "The acquire, release, or sequential relation attached to a memory operation.",
  GEMM: "General matrix multiplication, C = A x B, often implemented with tiled cooperative loads.",
  autoresearch: "A fixed-evaluator research loop in which an agent changes one bounded implementation surface, measures it, and keeps or rejects the change from evidence.",
  "experiment ledger": "An append-only record of candidate identity, hypothesis, correctness status, score, and keep or reject decision.",
  "search objective": "The fixed scalar metric used to rank only candidates that first pass every correctness and validity gate.",
  "geometric mean": "The nth root of the product of n positive measurements, used here so no single matrix size dominates the multi-shape score by scale alone.",
  tile: "A fixed submatrix or region assigned to a workgroup, wave, or lane fragment.",
  MFMA: "AMD matrix fused multiply-add instruction families.",
  "accumulator invariant": "A loop statement relating current accumulators to exactly the K phases processed so far.",
  "edge predicate": "A bounds guard for partial tiles at matrix or sequence boundaries.",
  "property ledger": "A review table mapping each assurance property to positive and negative evidence.",
  "translation validation": "Checking that a compiler output preserves a specific source or IR contract for that compilation.",
  "total correctness": "A theorem combining functional postconditions with termination and the absence of unhandled traps over its stated domain.",
  "numerical oracle": "An independent implementation used to evaluate result error under a stated policy.",
  softmax: "A normalized exponential mapping over a specified active row domain.",
  "max subtraction": "Subtracting a row maximum before exponentiation to improve numerical stability.",
  "error budget": "An explicit bound on acceptable numerical deviation and its assumptions.",
  masking: "Excluding specified positions from an operation's semantic domain.",
  "flash attention": "A tiled attention algorithm that combines score computation, online softmax, and value accumulation without materializing the full score matrix.",
  "online softmax": "An incremental max/sum representation that remains equivalent to softmax over the processed domain.",
  recurrence: "A base state and phase transition used to relate a loop or parallel phase trace to a sequential specification.",
  "causal mask": "A mask allowing a query to attend only to keys at permitted earlier or equal positions.",
  "numerical refinement": "A proved or tested relation between an abstract numeric model and target operations.",
  "mixture of experts": "A model layer routing each token to a bounded subset of expert networks.",
  "top-k": "Selection of the k greatest candidates under a total tie-breaking policy.",
  capacity: "A maximum accepted route count for an expert.",
  "stable rank": "A deterministic ordinal among accepted routes with the same expert.",
  permutation: "A mapping from token-major routes to compact expert-major storage.",
  "grouped GEMM": "A collection of matrix products with per-group dimensions or operands.",
  "inverse permutation": "A map returning compact expert outputs to original token and route coordinates.",
  "weighted combine": "The ordered sum of routed expert outputs multiplied by router weights.",
  "persistent kernel": "A long-lived kernel that obtains multiple work items dynamically, usually from a device queue.",
  "Kernel IR": "fe2o3's target-neutral canonical kernel representation and verifier boundary.",
  "ranked PLIRON": "PLIRON kernel IR whose memory objects and accesses carry rank, extents, indices, and source locations for generic verification.",
  Rejected: "A compiler-analysis result that proves a kernel violates a mandatory safety or semantic obligation.",
  Incomplete: "A fail-closed compiler-analysis result indicating that the supported model or resource budget cannot discharge a mandatory obligation.",
  "compiler-issued capability": "A non-forgeable typed witness created only by the compiler for an authenticated invocation, ownership partition, participant set, memory epoch, matrix context, or atomic view.",
  "compiler safety pass": "A workload-neutral verifier scheduled before target lowering that accepts, rejects, or reports an incomplete obligation.",
  LLVM: "The compiler infrastructure used to lower and optimize AMDGPU IR.",
  LLD: "LLVM's linker, used by the direct-link worker to produce code objects.",
  "machine-effect inspection": "Independent parsing of code-object ABI, resources, and instructions relevant to a claim.",
  "artifact binding": "Joining source, contracts, proofs, ABI, target, payload, and launch metadata to one executable identity.",
  Verified: "The intended label for all required authenticated property evidence plus compiler/runtime checks.",
  Checked: "Static and dynamic checks pass, but complete authenticated proof evidence is absent.",
  Unsafe: "At least one obligation is delegated to a documented unsafe caller.",
  "external body": "A Verus function whose implementation is trusted while its declared contract is assumed.",
  "assumption audit": "A review of premises, axioms, external bodies, abstractions, and trusted joins used by a theorem.",
  "vertical slice": "One bounded kernel path connected through source, compiler, artifact, runtime, and tests.",
  "acceptance contract": "The exact properties and evidence classes required before changing a maturity label.",
  canary: "Memory surrounding an allowed region used to detect out-of-bounds writes.",
  "signed evidence": "Canonical result data authenticated by a trusted signing key.",
  "protected policy": "Promotion rules and verifier inputs obtained from a protected base rather than candidate content.",
  "independent review": "A separate trusted signature over the exact evidence set required for Complete.",
  Complete: "A parity status requiring every row-specific acceptance class and protected signed evidence; absent at this baseline.",
  gfx950: "The AMD CDNA 4 processor target used by MI350 and MI355X accelerators; a gfx950 code object is not evidence that the current runtime device is gfx950.",
  FP4: "A four-bit floating-point operand format; these lessons use packed E2M1 values with explicit block-scale semantics.",
  FP8: "An eight-bit floating-point operand format; these lessons use packed E4M3 values with explicit block-scale semantics.",
  E8M0: "An exponent-only eight-bit block-scale format applied to a declared group of low-precision matrix elements.",
  "transpose load": "A format-specific gfx950 LDS read that rearranges packed fragment data into the register orientation consumed by a matrix instruction.",
  "expert-major layout": "A compact layout grouping accepted token routes by expert for local expert computation.",
  KDA: "A gated linear-attention family whose exact recurrent update must be taken from the named implementation, not inferred from the family name.",
  GDN: "A gated delta-network family with ordered recurrent state updates; the lesson does not imply equivalence to every GDN formulation.",
  "linear attention": "An attention formulation represented through a bounded state recurrence rather than a materialized full score matrix.",
  "recurrent state": "State carried between ordered sequence steps under an explicit initialization and update rule.",
  "indexed sparse attention": "Attention over key/value positions selected by an explicit bounded index table.",
  "gather contract": "The bounds, invalid-index, duplicate, ordering, and multiplicity rules for indexed reads.",
  "duplicate semantics": "The declared treatment of repeated logical indices, including whether each occurrence contributes independently.",
  "compressed attention": "An attention branch that summarizes a declared input domain into a smaller state before readout.",
  "hybrid attention": "An explicit combination of two or more attention branches with separately stated domains and fusion rules.",
  "fusion contract": "The coordinate alignment, coefficient, numeric type, and operation order used to combine branch outputs.",
  "model equivalence": "A demonstrated relation between a bounded operator implementation and the complete model-level computation; no advanced lesson claims it.",
  AttnRes: "An attention-residual mixing family whose exact stream selection and coefficients are source-defined.",
  GR: "A gated-residual mixing family; the exact gate transform and update order are part of the kernel contract.",
  mHC: "A multi-stream residual mixing family; this curriculum treats its matrix and normalization behavior as source-defined.",
  "residual mixing": "Combining named residual streams through explicit gates or mixing coefficients while preserving required inputs.",
  "speculative decoding": "Drafting candidate tokens and verifying a deterministic accepted prefix against a target computation.",
  MTP: "Multi-token prediction; this lesson covers only the fixed-width verification kernel, not a complete decoding system.",
  "accepted prefix": "The consecutive candidate positions accepted before the first rejection under a declared verification rule.",
  "verification kernel": "A bounded operator computing verification predicates and outputs, separate from scheduling, sampling, and serving control.",
  "N-gram": "A fixed-order contiguous token sequence used as a lookup key under explicit boundary rules.",
  "embedding gather": "Resolving bounded table rows and loading embedding components; the current N-gram teaching kernel stops at an integer table value.",
  "hash-table gather": "Probing a bounded hash table, comparing exact keys, resolving matches, and returning the selected table value.",
  "lookup miss": "A lookup key with no admitted table row, handled by an explicit sentinel, mask, or fallback value.",
  Muon: "An optimizer family using a matrix orthogonalization transform; the current teaching kernel emits an update without momentum or parameter application.",
  orthogonalization: "A bounded matrix transform intended to move an update toward an orthogonal form under a stated numeric policy.",
  momentum: "Optimizer state updated from previous state and the current gradient under a named convention.",
  "optimizer state": "Mutable state carried between optimizer steps, with explicit initialization, precision, and ownership.",
  "polar iteration": "One bounded matrix update toward a polar factor; the Muon teaching kernel uses five Newton-Schulz-like iterations.",
  "gradient shard": "One ordered partial gradient matrix staged for a later fixed reduction.",
  "optimizer update": "The emitted scaled update tensor; the teaching kernel does not apply it to parameter or momentum state.",
};

export const glossary: GlossaryEntry[] = Array.from(
  new Map(
    lessons.flatMap((lesson) =>
      lesson.glossary.map((term) => [
        term.toLowerCase(),
        {
          term,
          definition:
            definitions[term] ??
            `A curriculum term introduced in ${lesson.title}.`,
          lessonId: lesson.id,
        } satisfies GlossaryEntry,
      ]),
    ),
  ).values(),
).sort((left, right) => left.term.localeCompare(right.term));
