import type { CodeTab } from "./model";

interface AdvancedPerformanceRecord {
  lessonId: string;
  evidencePath: string;
  lines: string[];
}

const boundedClaim = [
  "CLAIM BOUNDARY",
  "These are fixed-shape MI350X measurements, not universal state-of-the-art claims.",
  "State-of-the-art claim: not claimed; fastest statements are limited to admitted variants.",
  "A fastest statement applies only to the exact admitted artifacts and protocol named below.",
  "Framework, full-model, multi-workgroup, and differently shaped implementations are not comparable here.",
];

const evidence = "perf-evidence/gfx950-advanced-ablation-evidence-v1.json";

const protocol = [
  "FINAL ABLATION PROTOCOL",
  "Host: smci350-rck-g03-b19-03; physical GPU 6; gfx950:xnack-; HIP_VISIBLE_DEVICES unset",
  "Measured source: da6c108d162bac8afd79e789ccf9b36ef8eb97a4; promoted production source: 4f9b2bf09db41e6ef38db1bb926c2fa7989d8e1f",
  "One process per variant; 1,000 warmups; 30 blocks x 100 samples; 20 block-rewarm dispatches",
  "Timer: ROCr HSA dispatch timestamps; hierarchical bootstrap with 10,000 repetitions and seed 950",
  "Correctness: independent CPU reference, immutable-input checks, guard canaries, preflight dispatch, and post-block validation",
  "Campaign: 32 exact HSACOs, 35 timing series, 105,000 dispatch samples, and zero retained AMDGPU target directories",
];

const records: AdvancedPerformanceRecord[] = [
  {
    lessonId: "gfx950-advanced-moe",
    evidencePath: `${evidence}; examples/gfx950_advanced_systems/ablation-variants-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "OPTIMIZATION [route-packed-reuse]: Compute each route once, broadcast stable top-2 choices, and reuse the packed route map.",
      "IMPACT [route-packed-reuse]: Measured production median 19,600 ns; three owner-only, per-record-broadcast, and u32-pack alternatives were rejected as noncanonical or compiler-invalid, so no fabricated marginal speedup is reported.",
      "OPTIMIZATION [expert-software-schedule]: Load three independent activation/weight streams before issuing mixed FP4/FP8 MFMAs.",
      "IMPACT [expert-software-schedule]: Measured serial -> eager medians were 38,520 -> 38,041 ns for rank 0 and 38,160 -> 37,720 ns for rank 1, reductions of 1.2435% and 1.1530%.",
      "OPTIMIZATION [expert-native-tile]: Use three gfx950 m16n16k128 mixed FP4/FP8 MFMAs in one Wave64.",
      "IMPACT [expert-native-tile]: Static ISA validation found exactly three scaled MFMAs with cbsz:4 and no scalar low-precision fallback; timing contribution is unavailable because no exact non-MFMA baseline was admitted.",
      "OPTIMIZATION [combine-ownership]: Keep exact 256-thread combine ownership rather than a transposed one-wave map.",
      "IMPACT [combine-ownership]: Measured canonical median 5,040 ns; the transpose alternative was compiler-rejected because its subgroup source lane was not statically bounded.",
      "KERNEL: gfx950_moe_route_fp4_t16_e4_k2_v1",
      "KERNEL: gfx950_moe_expert_rank_fp4_fp8_v1",
      "KERNEL: gfx950_combine_expert_ranks_v1",
      "WORKLOAD BOUNDS: 16 tokens, hidden 128, output 16, four routed experts, one shared expert, stable top-2 routing, and one fixed dispatch tile.",
      "SOFTWARE PIPELINE ASSESSMENT: Used for the three independent expert load/MFMA streams; route and combine remain dependency-bound.",
      "LDS MULTI-BUFFER ASSESSMENT: Inapplicable because each expert stream has one K=128 tile and route/combine have no repeated producer-consumer tile.",
      "TILE SHAPE ASSESSMENT: Retained Wave64 m16n16k128 expert work and exact 256-thread route/combine ownership; rejected maps did not pass the proof gate.",
      ...protocol,
      "THEORETICAL RESOURCE FLOORS",
      "Derivation: max(compulsory bytes / 8 TB/s, counted FP32 ops / 144.2 TFLOP/s, mixed ops / 4.6 PFLOP/s).",
      "Route floor 0.610 ns and measured/floor 32,131x; expert floor 1.184 ns and rank-0 measured/floor 32,129x; combine floor 0.384 ns and measured/floor 13,125x.",
      "ADMITTED COMPARATOR RESULT",
      "Eager expert scheduling is fastest among its two exact schedules. Route and combine expose the retained artifact plus documented compiler rejections.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-kda-gdn-linear-attention",
    evidencePath: `${evidence}; examples/gfx950_advanced_attention/ablation-variants-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "OPTIMIZATION [decode-wave16-groups]: Replicate the 16-channel decode map over four wave16 groups.",
      "IMPACT [decode-wave16-groups]: Measured 3,760 -> 5,040 ns, a 32.9787% regression; the four-group artifact was rejected despite fewer static instructions.",
      "OPTIMIZATION [prefill-channel-mask]: Replace channel modulo 16 with channel & 15.",
      "IMPACT [prefill-channel-mask]: Compiler-equivalent byte-identical HSACO 58536eb9... makes the machine-code contribution exactly zero; 6,200 vs 6,160 ns is sequential-run noise, not attributed speedup.",
      "OPTIMIZATION [prefill-ping-pong]: Double-buffer consecutive recurrent states.",
      "IMPACT [prefill-ping-pong]: Rejected because token t+1 consumes state produced by token t, leaving no independent next state to prefetch.",
      "KERNEL: gfx950_kda_gdn_decode",
      "KERNEL: gfx950_kda_gdn_prefill",
      "WORKLOAD BOUNDS: decode has 16 channels and three causal taps; prefill carries 16 state values through eight ordered tokens.",
      "SOFTWARE PIPELINE ASSESSMENT: Rejected because state, exponentials, reduction, and reciprocal square root form a loop-carried chain.",
      "LDS MULTI-BUFFER ASSESSMENT: Inapplicable because the fixed state is register-resident with no independent memory tile.",
      "TILE SHAPE ASSESSMENT: Retained one canonical 16-channel Wave64 map; four-wave16 replication regressed 32.9787%.",
      ...protocol,
      "THEORETICAL RESOURCE FLOORS",
      "Decode derivation: max(460 B / 8 TB/s, 321 FP32 ops / 144.2 TFLOP/s) = 0.0575 ns; 3,760 ns is 65,391x the floor.",
      "Prefill derivation: max(1,676 B / 8 TB/s, 2,472 FP32 ops / 144.2 TFLOP/s) = 0.2095 ns; 6,160 ns is 29,403x the floor.",
      "ADMITTED COMPARATOR RESULT",
      "Canonical decode is fastest among two exact decode artifacts. The prefill source forms are one identical machine artifact.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-indexed-sparse-attention",
    evidencePath: `${evidence}; examples/gfx950_advanced_attention/ablation-variants-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "OPTIMIZATION [sparse-native-mfma]: Stage one E4M3 key tile in 2,048 B LDS, issue four B8 transpose reads, then one m16n16k128 FP8 MFMA.",
      "IMPACT [sparse-native-mfma]: Static validation found exactly four ds_read_b64_tr_b8 instructions before one scaled FP8 MFMA and no scalar fallback; an exact scalar candidate was compiler-rejected.",
      "OPTIMIZATION [sparse-reciprocal]: Replace three normalized divisions with one reciprocal.",
      "IMPACT [sparse-reciprocal]: Measured 22,320 -> 22,361 ns; paired speedup 0.994662 with CI [0.994643, 0.996416], a 0.5367% regression, so it was rejected.",
      "OPTIMIZATION [sparse-lds-pingpong]: Add a second 2,048 B LDS stage with prefetch distance one.",
      "IMPACT [sparse-lds-pingpong]: Inapplicable because K=128 is exactly one native tile; a second stage duplicates data and adds synchronization.",
      "OPTIMIZATION [sparse-tile-tuning]: Vary the native tile while preserving exact 16x16x128 work.",
      "IMPACT [sparse-tile-tuning]: Unavailable because the admitted API exposes a single exact tile shape and extra MFMAs change executed work.",
      "KERNEL: gfx950_content_sparse_attention",
      "WORKLOAD BOUNDS: 16 tokens, head dimension 128, 16 value channels, top two of four blocks, then top three token IDs.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because one QK tile feeds serial selection, softmax, and PV work.",
      "LDS MULTI-BUFFER ASSESSMENT: Rejected because a second stage duplicates the only key tile.",
      "TILE SHAPE ASSESSMENT: Retained one exact m16n16k128 FP8 MFMA with four gfx950 transpose reads.",
      ...protocol,
      "THEORETICAL RESOURCE FLOOR",
      "Derivation: max(4,492 B / 8 TB/s, 65,536 FP8 FLOPs / 4.6 PFLOP/s, 169 scalar ops / 144.2 TFLOP/s) = 0.5615 ns; 22,320 ns is 39,751x the floor.",
      "ADMITTED COMPARATOR RESULT",
      "The retained division artifact is fastest among the two exact sparse arithmetic variants.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-compressed-hybrid-attention",
    evidencePath: `${evidence}; examples/gfx950_advanced_attention/ablation-variants-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "OPTIMIZATION [hybrid-reciprocal]: Reuse one reciprocal across four local weights and one across three compressed-global weights.",
      "IMPACT [hybrid-reciprocal]: Measured 22,800 -> 22,560 ns, paired 1.007105x with CI [1.005378, 1.008818], a 0.7055% reduction; promoted into production.",
      "OPTIMIZATION [hybrid-promotion-proof]: Rebuild production and the renamed division baseline after promotion.",
      "IMPACT [hybrid-promotion-proof]: Measured 22,760 -> 22,640 ns over 500 samples, paired 1.005300x with CI [1.003534, 1.007080]; production reproduced winning HSACO 3cf9a73d... byte-for-byte.",
      "OPTIMIZATION [hybrid-fusion]: Keep local and compressed-global branches in one launch around one FP8 MFMA.",
      "IMPACT [hybrid-fusion]: Static fusion is retained, but isolated latency contribution is unavailable because materializing intermediates changes ABI and traffic.",
      "OPTIMIZATION [hybrid-lds-pingpong]: Double-buffer key tiles around the FP8 MFMA.",
      "IMPACT [hybrid-lds-pingpong]: Inapplicable because K=128 supplies one native tile; no next tile exists to overlap.",
      "KERNEL: gfx950_compressed_hybrid_attention",
      "WORKLOAD BOUNDS: 16 tokens, head dimension 128, 16 value channels, three compressed blocks, and tokens 12-15 as the local window.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because the sole QK tile completes before both dependent branches.",
      "LDS MULTI-BUFFER ASSESSMENT: Rejected because a second 2,048 B stage duplicates the only K tile.",
      "TILE SHAPE ASSESSMENT: Retained native m16n16k128 FP8; the scalar seven-score alternative was compiler-rejected.",
      ...protocol,
      "THEORETICAL RESOURCE FLOOR",
      "Derivation: max(4,480 B / 8 TB/s, 65,536 FP8 FLOPs / 4.6 PFLOP/s, 529 scalar ops / 144.2 TFLOP/s) = 0.5600 ns; 22,560 ns is 40,286x the floor.",
      "ADMITTED COMPARATOR RESULT",
      "Promoted reciprocal reuse is fastest among exact division and reciprocal artifacts in both final and post-promotion runs.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-attnres-gr-mhc",
    evidencePath: `${evidence}; examples/gfx950_advanced_attention/ablation-variants-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "OPTIMIZATION [attnres-explicit]: Replace the four-depth loop with explicit logits and weights.",
      "IMPACT [attnres-explicit]: Measured 5,000 -> 5,040 ns; paired CI [0.992063, 1.0] includes parity, so it was not promoted.",
      "OPTIMIZATION [four-branch-explicit]: Replace the four-branch loop with explicit sigmoid-gated branches.",
      "IMPACT [four-branch-explicit]: Measured 5,000 -> 5,000 ns with paired CI [1.0, 1.0], an exact timing tie.",
      "OPTIMIZATION [mhc-wave16-distribution]: Distribute the rotated 4x4 matrix over four wave16 groups.",
      "IMPACT [mhc-wave16-distribution]: Measured scalar 7,240 -> distributed 5,000 ns, a 1.448x speedup and 30.9392% reduction; instructions 1,750 -> 457, VGPRs 34 -> 12, SGPRs 34 -> 22.",
      "OPTIMIZATION [mhc-reciprocal-reuse]: Reuse one reciprocal per four-element row normalization.",
      "IMPACT [mhc-reciprocal-reuse]: Static divides and reciprocal instructions fell 96 -> 6; independent latency is unavailable because distribution and reuse were timed together.",
      "OPTIMIZATION [mixing-lds-stage]: Stage four-element reductions through LDS.",
      "IMPACT [mixing-lds-stage]: Rejected because working sets fit in registers; LDS adds stores, loads, and barriers without reuse.",
      "KERNEL: gfx950_attnres_aggregate",
      "KERNEL: gfx950_four_branch_residual",
      "KERNEL: gfx950_mhc_sinkhorn_mix",
      "WORKLOAD BOUNDS: 16 channels; four AttnRes depths, four residual branches, four mHC streams, and three Sinkhorn iterations.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because every normalization and Sinkhorn iteration consumes the preceding reduction.",
      "LDS MULTI-BUFFER ASSESSMENT: Rejected because four-element working sets are register-resident.",
      "TILE SHAPE ASSESSMENT: Retained one Wave64 over exact 4x16 and 4x4 shapes.",
      ...protocol,
      "THEORETICAL RESOURCE FLOORS",
      "AttnRes: max(576 B / 8 TB/s, 288 / 144.2 TFLOP/s) = 0.072 ns and measured/floor 69,444x; four-branch: 0.080 ns and 62,500x; mHC: 0.072 ns and 69,444x.",
      "ADMITTED COMPARATOR RESULT",
      "Distributed mHC is fastest among two exact artifacts; AttnRes explicit is indistinguishable and four-branch explicit ties.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-speculative-mtp-verification",
    evidencePath: `${evidence}; examples/gfx950_advanced_systems/ablation-variants-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "OPTIMIZATION [prefix-broadcast]: Compute each accepted prefix once and broadcast it to eight state elements.",
      "IMPACT [prefix-broadcast]: Measured recompute 5,800 -> broadcast 5,760 ns, a 1.006944x speedup and 0.6897% reduction; distinct HSACOs prove the ablation exercised live code.",
      "OPTIMIZATION [transaction-fusion]: Validate four draft steps and commit state in one dispatch.",
      "IMPACT [transaction-fusion]: Measured production median 5,760 ns; an exact materialized baseline is unavailable because extra state buffers change the contract.",
      "OPTIMIZATION [transaction-prefetch]: Prefetch the next candidate during the current prefix.",
      "IMPACT [transaction-prefetch]: Inapplicable because every prefix predicate consumes the preceding draft-step result.",
      "KERNEL: gfx950_speculative_transaction_v1",
      "WORKLOAD BOUNDS: eight candidates, four ordered draft steps, and eight state elements with all-or-nothing commit.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because draft predicates form a serial acceptance chain.",
      "LDS MULTI-BUFFER ASSESSMENT: Inapplicable because fixed state is register-resident with no repeated global tile.",
      "TILE SHAPE ASSESSMENT: Retained one Wave64 over exact eight-candidate by four-step work.",
      ...protocol,
      "THEORETICAL RESOURCE FLOOR",
      "Derivation: max(1,664 B / 8 TB/s, 256 FP32 ops / 144.2 TFLOP/s) = 0.208 ns; 5,760 ns is 27,692x the floor.",
      "ADMITTED COMPARATOR RESULT",
      "Prefix broadcast is fastest among exact broadcast and live-recomputation artifacts.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-ngram-embedding-gather",
    evidencePath: `${evidence}; examples/gfx950_advanced_systems/ablation-variants-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "OPTIMIZATION [ascending-probe]: Probe the 16-slot table in ascending order with canonical early exit.",
      "IMPACT [ascending-probe]: Measured reverse 9,800 -> ascending 8,480 ns, a 1.15566x speedup and 13.4694% reduction.",
      "OPTIMIZATION [full-key-check]: Keep the exact three-token collision check.",
      "IMPACT [full-key-check]: Static exactness is retained; independent timing is unavailable because removing the key check changes semantics.",
      "OPTIMIZATION [table-lds-stage]: Copy the 16-slot table into LDS before probing.",
      "IMPACT [table-lds-stage]: Inapplicable for one wave and one query batch because it adds a copy and barrier without second-tile reuse.",
      "KERNEL: gfx950_qwen_ngram_gather_v1",
      "WORKLOAD BOUNDS: eight queries, three tokens per N-gram, 16 slots, and one integer result per query.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because each probe address and exact-key decision consumes the prior result.",
      "LDS MULTI-BUFFER ASSESSMENT: Inapplicable because the table is one bounded gather domain, not a repeated tile.",
      "TILE SHAPE ASSESSMENT: Retained eight queries over 16 slots; reverse order was measured and rejected.",
      ...protocol,
      "THEORETICAL RESOURCE FLOOR",
      "Derivation: 576 B / 8 TB/s = 0.072 ns; 8,480 ns is 117,778x the optimistic bandwidth floor.",
      "ADMITTED COMPARATOR RESULT",
      "Ascending probe order is fastest among exact ascending and reverse-order artifacts.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-muon-optimizer",
    evidencePath: `${evidence}; examples/gfx950_advanced_systems/ablation-variants-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "OPTIMIZATION [stage-wave64]: Copy each exact 4x4 gradient shard with one Wave64 map.",
      "IMPACT [stage-wave64]: Measured stage medians are 5,000 ns; tile4 was compiler-rejected because its subgroup source lane was not statically bounded.",
      "OPTIMIZATION [muon-distribution]: Assign one 4x4 element per lane and exchange reductions instead of evaluating the full update per lane.",
      "IMPACT [muon-distribution]: Prior exact scalar -> distributed measurement was 5,720 -> 5,040 ns, a 1.135x speedup; instructions 1,360 -> 593, VALU 969 -> 160, VGPRs 62 -> 19, SGPRs 58 -> 22.",
      "OPTIMIZATION [muon-broadcast16]: Replace canonical reduction exchange with wave16 broadcasts.",
      "IMPACT [muon-broadcast16]: Final aggregate medians tied at 5,000 ns; a 0.8% paired movement is below robust marginal attribution, so canonical was retained.",
      "OPTIMIZATION [muon-iteration-pipeline]: Overlap adjacent polar iterations or double-buffer the 4x4 iterate.",
      "IMPACT [muon-iteration-pipeline]: Inapplicable because each of five iterations consumes the preceding matrix and the working set stays in registers.",
      "KERNEL: gfx950_stage_gradient_shard_v1",
      "KERNEL: gfx950_muon_update_4x4_v1",
      "WORKLOAD BOUNDS: two gradient shards reduce into one 4x4 FP32 matrix, followed by five polar iterations.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because each polar iteration consumes the preceding iterate.",
      "LDS MULTI-BUFFER ASSESSMENT: Inapplicable because the 4x4 matrix remains in registers and Wave64 exchanges.",
      "TILE SHAPE ASSESSMENT: Retained one element per lane over exact 4x4; stage tile4 was compiler-rejected.",
      ...protocol,
      "THEORETICAL RESOURCE FLOORS",
      "Stage derivation: 128 B / 8 TB/s = 0.016 ns and measured/floor 312,500x. Muon: max(196 B / 8 TB/s, 1,649 / 144.2 TFLOP/s) = 0.0245 ns and measured/floor 204,082x.",
      "ADMITTED COMPARATOR RESULT",
      "Distributed Muon beats the prior exact scalar artifact. Broadcast16 did not establish a robust gain; stage tile4 did not compile.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-gpt-oss-120b-megakernel",
    evidencePath: `${evidence}; examples/gfx950_gpt_oss_decode/ablation-variants-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "OPTIMIZATION [parallel-router]: Assign two of 128 logits per Wave64 lane and merge stable top-4 choices.",
      "IMPACT [parallel-router]: Measured serial 58.323676 ms -> optimized full kernel 1.065004 ms, a 54.7638x speedup and 98.1743% reduction.",
      "OPTIMIZATION [dispatch-fusion]: Fuse exact router, BF16 attention, MXFP4 expert projection, and disjoint stores.",
      "IMPACT [dispatch-fusion]: Measured exact Rust component sum 1.251325 ms -> fused 1.065004 ms, a 1.17648x ratio and 14.8899% reduction.",
      "OPTIMIZATION [sequential-fragments]: Construct and consume each MXFP4 accumulator before the next.",
      "IMPACT [sequential-fragments]: Measured held 1.065404 ms -> sequential 1.065004 ms; paired reduction 0.1465%, VGPRs 352 -> 308, AGPRs 96 -> 52.",
      "OPTIMIZATION [grouped-stores]: Commit three outputs as grouped disjoint stores.",
      "IMPACT [grouped-stores]: Aggregate medians favor grouped 1.065004 ms over interleaved 1.065524 ms, while paired ordering favors interleaving by 0.139%; unresolved, so grouped remains.",
      "OPTIMIZATION [bf16-lds-pipeline]: Prime, loop, and drain two 2,048 B LDS stages with prefetch distance one.",
      "IMPACT [bf16-lds-pipeline]: Compiler-rejected at ranked projection after the exact two-stage implementation; no timing is claimed.",
      "OPTIMIZATION [fp4-lds-pipeline]: Apply the sealed pipeline to gfx950 FP4 fragments.",
      "IMPACT [fp4-lds-pipeline]: Unavailable in the admitted API because the sealed pipeline element surface lacks an FP4 implementation.",
      "OPTIMIZATION [gpt-tile-tuning]: Compare alternate BF16 and FP4 MFMA shapes.",
      "IMPACT [gpt-tile-tuning]: Unavailable because the admitted API supports only BF16 m16n16k16 and low-precision m16n16k128 Wave64 shapes.",
      "KERNEL: gfx950_gpt_oss_120b_decode_megakernel_v1",
      "WORKLOAD BOUNDS: batch 1; hidden 512; 128 experts; top 4; 16 attention tokens/channels; one Wave64 layer tile, not the full model.",
      "SOFTWARE PIPELINE ASSESSMENT: Rejected for the implemented BF16 two-stage candidate; the fused dependency chain remains register-resident.",
      "LDS MULTI-BUFFER ASSESSMENT: Compiler-rejected for BF16 and unavailable for FP4 on the production-safe surface.",
      "TILE SHAPE ASSESSMENT: Retained BF16 m16n16k16 plus MXFP4 m16n16k128; no alternate exact tile lowered.",
      ...protocol,
      "THEORETICAL RESOURCE FLOOR",
      "Derivation: max(1,509,972 B / 8 TB/s, 745,472 FP32 ops / 144.2 TFLOP/s, 262,144 MXFP4 ops / 9.2 PFLOP/s) = 188.7465 ns; 1.065004 ms is 5,642.5x the floor.",
      "ADMITTED COMPARATOR RESULT",
      "The fused stack beats serial routing, held fragments, and the exact three-dispatch Rust component sum for this tile. Store ordering is unresolved; no whole-model or universal SoTA claim is made.",
      ...boundedClaim,
    ],
  },
];

export const advancedPerformanceLessonIds = records.map(
  (record) => record.lessonId,
);

export function advancedPerformanceTabFor(
  lessonId: string,
): CodeTab | undefined {
  const record = records.find((candidate) => candidate.lessonId === lessonId);
  if (!record) return undefined;
  return {
    kind: "performance",
    label: "Performance",
    language: "text",
    code: [
      "FE2O3 GFX950 BOUNDED PERFORMANCE EVIDENCE",
      `Evidence source: ${record.evidencePath}`,
      "",
      ...record.lines,
    ].join("\n"),
    explanatory: true,
    notice:
      "Bounded MI350X ablation evidence. Comparator scope, protocol limits, correctness gates, and resource-floor assumptions are part of the record; no universal state-of-the-art claim is made.",
  };
}
