import type { CodeTab } from "./model";

interface AdvancedPerformanceRecord {
  lessonId: string;
  evidencePath: string;
  lines: string[];
}

const boundedClaim = [
  "CLAIM BOUNDARY",
  "These are fixed-shape MI350X measurements, not universal state-of-the-art claims.",
  "A fastest statement applies only to the exact admitted artifacts and protocol named below.",
  "Framework, full-model, multi-workgroup, and differently shaped implementations are not comparable here.",
];

const finalAdvancedEvidencePath = "perf-evidence/gfx950-advanced-evidence-v1.json";

const finalCandidateProtocol = [
  "FINAL CURRENT-PRODUCTION CAMPAIGN",
  "Host: smci350-rck-g03-b19-03; physical GPU 6; gfx950:xnack-; ROCm 7.2.1",
  "Source: campaign commit 66f9467353400d32ed045d00fabbacc6c5575496; kernel source commit c1383e97db732f9f1ff8105f10d5c2b5971143e1",
  "Timer: ROCr HSA dispatch timestamps at 1 GHz",
  "One process per series; 1,000 warmups; 30 blocks x 100 samples; 20 untimed block-rewarm dispatches",
  "Bootstrap: hierarchical process/block resampling with within-block resampling; 10,000 repetitions; seed 950",
  "Correctness gate: CPU reference, immutable inputs, guard canaries, preflight dispatch, and post-block checks",
  "Claim limit: candidate-only measurements; no new baseline, speedup, fastest-kernel, or state-of-the-art conclusion",
];

const records: AdvancedPerformanceRecord[] = [
  {
    lessonId: "gfx950-advanced-moe",
    evidencePath: `${finalAdvancedEvidencePath}; examples/gfx950_advanced_systems/optimization-evidence-v1.json`,
    lines: [
      "OPTIMIZATION STACK",
      "OPTIMIZATION [route-once-reuse]: Compute each token route once per wave, broadcast the stable top-2 choices, and reuse the packed route map.",
      "IMPACT [route-once-reuse]: Final production median 19.640 us with HSACO 31f1f76b...; latency contribution is unavailable because no exact independent route baseline was admitted.",
      "OPTIMIZATION [expert-wave64-blocking]: Use one Wave64, four-element blocked ownership, and three mixed FP4/FP8 MFMAs per expert-rank tile.",
      "IMPACT [expert-wave64-blocking]: Rank medians are 39.560 us and 39.160 us with HSACO 7e8e1cb5...; contribution is unavailable because no exact independent expert baseline was admitted.",
      "OPTIMIZATION [combine-blocked-map]: Test a one-wave blocked combine map against the exact 256-thread ownership map.",
      "IMPACT [combine-blocked-map]: Rejected due to proof failure; the retained exact map tied its admitted baseline at 5.00 us, a 0 ns contribution, with 291 instructions, 5 VGPRs, and 22 SGPRs.",
      "KERNEL: gfx950_moe_route_fp4_t16_e4_k2_v1",
      "Route: compute each token route once per wave, broadcast the choices, and reuse a packed route map.",
      "  Measured production candidate: median 19.640 us; bootstrap 95% CI [19.640, 19.640] us; p5/p95 19.520/19.760 us; HSACO 31f1f76bda88c340bcb9dcbba4323a3ea5a996ceba27d5fe9e6f2f43da826deb.",
      "  No admitted baseline/candidate pair exists; latency contribution and fastest status remain unavailable.",
      "KERNEL: gfx950_moe_expert_rank_fp4_fp8_v1",
      "Expert rank: one Wave64 with four-element blocked ownership and three mixed FP4/FP8 MFMAs.",
      "  Measured production candidates: rank 0 median 39.560 us [39.520, 39.560], p5/p95 39.200/39.960 us; rank 1 median 39.160 us [39.120, 39.200], p5/p95 38.800/39.560 us; shared HSACO 7e8e1cb59473e52949ded2e6d5e737d3b7e4cc27a834052da01d4e41cddeb504.",
      "  No admitted baseline/candidate pair exists; latency contribution and fastest status remain unavailable.",
      "KERNEL: gfx950_combine_expert_ranks_v1",
      "Combine: a one-wave blocked mapping was rejected after proof failure; the exact 256-thread mapping was retained.",
      "  Final production candidate: median 5.000 us; bootstrap 95% CI [5.000, 5.000] us; p5/p95 4.398/5.123 us; HSACO aa5aa7fa613ae8f439dcf8b626ce18b7560f9705453bd3b9f0ddbc936501166e.",
      "  Prior isolated comparison: baseline 5.00 us [4.96, 5.00]; retained 5.00 us [4.96, 5.00]; contribution 0 ns, 1.00x.",
      "  Static ISA is unchanged: 291 instructions, 5 VGPRs, 22 SGPRs.",
      "",
      "WORKLOAD BOUNDS: 16 tokens, hidden 128, output 16, four routed experts plus one shared expert, and stable top-2 routing.",
      "SOFTWARE PIPELINE ASSESSMENT: Unavailable because no exact independent multi-stage baseline artifact was admitted for route, expert, or combine.",
      "LDS MULTI-BUFFER ASSESSMENT: Inapplicable because these fixed single-wave stages expose no repeated K-tile load sequence to overlap.",
      "TILE SHAPE ASSESSMENT: Retained fixed token-16, hidden-128, output-16 ownership; the rejected one-wave combine map did not pass the proof gate.",
      ...finalCandidateProtocol,
      "",
      "THEORETICAL RESOURCE FLOORS",
      "Formula: max(logical bytes / 8 TB/s, FP32 ops / 144.2 TFLOP/s, mixed FP4/FP8 ops / 4.6 PFLOP/s).",
      "Route: max(4,880 B / 8 TB/s, 16,384 FP32 ops / 144.2 TFLOP/s) = 0.610 ns; measured ratio unavailable.",
      "Expert rank: max(9,472 B / 8 TB/s, 196,608 mixed ops / 4.6 PFLOP/s) = 1.184 ns; measured ratio unavailable.",
      "Combine: max(3,072 B / 8 TB/s, 256 FP32 ops / 144.2 TFLOP/s) = 0.384 ns; retained/floor = 13,021x.",
      "The floors assume fully occupied whole-device resources and exclude dispatch, dependencies, and cache effects.",
      "",
      "ADMITTED COMPARATOR RESULT",
      "Combine ties its one exact previously admitted baseline. Route and expert rank now have measured production candidates but no admitted timing comparison.",
      "The machine-readable systems record predates the later production-lowering fixes for route and expert rank; its blocker fields are historical, not current compile status.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-kda-gdn-linear-attention",
    evidencePath: `${finalAdvancedEvidencePath}; examples/gfx950_advanced_attention/run-kda-decode-gfx950.sh and run-kda-prefill-gfx950.sh`,
    lines: [
      "OPTIMIZATION STACK",
      "OPTIMIZATION [decode-wave16-groups]: Repeat the 16-channel decode mapping in four wave16 groups and let the first group own stores.",
      "IMPACT [decode-wave16-groups]: Preliminary GPU3 median 3,480 ns -> 5,040 ns, a 44.83% regression; instructions 467 -> 443, VGPRs 13 -> 14, SGPRs 34 -> 34, and LDS remains 0 B, so the canonical mapping was retained.",
      "OPTIMIZATION [prefill-channel-mask]: Replace channel modulo 16 with a bit mask in the eight-token prefill recurrence.",
      "IMPACT [prefill-channel-mask]: Compiler-equivalent and byte-identical HSACO 58536eb9...; both paths have 1,209 instructions, 36 VGPRs, 38 SGPRs, and 0 B LDS, so contribution is exactly 0 ns after lowering.",
      "OPTIMIZATION [prefill-ping-pong]: Attempt to overlap consecutive prefill state updates with ping-pong storage.",
      "IMPACT [prefill-ping-pong]: Rejected because token t+1 requires the state produced by token t; the serial recurrence exposes no independent next state to prefetch.",
      "PRELIMINARY ABLATION PROTOCOL: physical GPU 3; one process; 100 warmups; 5 blocks x 100 samples; 10 block-rewarm dispatches. Final production values below remain pinned and unchanged.",
      "KERNEL: gfx950_kda_gdn_decode",
      "Optimization stack: one lane per channel, a Wave64 subgroup reduction over each 16-channel group, and one reciprocal-square-root result reused by the normalized store.",
      "Preliminary decode comparison: canonical p5/p95 3,440/3,520 ns; wave16-groups p5/p95 4,640/5,360 ns; exact CPU-oracle and canary checks passed for both artifacts.",
      "Measured production candidate: median 5.000 us; bootstrap 95% CI [5.000, 5.000] us; p5/p95 4.560/5.240 us; HSACO 5a16d32486c6a424c680ec200a8fcc6941115f3a2953ec6a7fad0e383ce4a6d5.",
      "This candidate-only measurement admits no baseline, speedup, fastest-kernel, or state-of-the-art conclusion.",
      "THEORETICAL RESOURCE FLOORS",
      "Decode: max(460 B / 8 TB/s, 321 FP32 ops / 144.2 TFLOP/s) = 0.0575 ns; the canonical preliminary median is 60,522x this strict floor.",
      "Decode also has 32 exponentials and one reciprocal square root; the floor excludes their serial latency and dispatch overhead.",
      "",
      "KERNEL: gfx950_kda_gdn_prefill",
      "Optimization stack: keep the eight-token recurrence in registers per channel, use subgroup reductions for each RMS normalization, and write the row-striped output once.",
      "Preliminary prefill observation: median 5,920 ns, p5/p95 5,880/5,960 ns; the mask and modulo forms compile to the same artifact.",
      "Measured production candidate: median 6.160 us; bootstrap 95% CI [6.160, 6.160] us; p5/p95 6.120/6.200 us; HSACO 58536eb9abf290821b3d85d39c262ed5b49ac8d835ee959b2c36fa9446998bfa.",
      "This candidate-only measurement admits no baseline, speedup, fastest-kernel, or state-of-the-art conclusion.",
      "Prefill: max(1,676 B / 8 TB/s, 2,472 FP32 ops / 144.2 TFLOP/s) = 0.2095 ns; the preliminary median is 28,258x this floor.",
      "Prefill also has 256 exponentials and eight reciprocal square roots on an eight-step serial dependency chain.",
      "",
      "WORKLOAD BOUNDS: decode has 16 channels and three causal taps; prefill carries 16 state values through eight ordered tokens.",
      "SOFTWARE PIPELINE ASSESSMENT: Rejected because the state recurrence makes consecutive prefill tokens dependent.",
      "LDS MULTI-BUFFER ASSESSMENT: Inapplicable because the fixed recurrence is register-resident and has no repeated independent memory tile.",
      "TILE SHAPE ASSESSMENT: Retained the canonical 16-channel map; the four-wave16-group mapping was measured and rejected.",
      "ADMITTED COMPARATOR RESULT",
      "None. The lesson makes no fastest-kernel claim for either KDA/GDN kernel.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-indexed-sparse-attention",
    evidencePath: `${finalAdvancedEvidencePath}; examples/gfx950_advanced_attention/run-content-sparse-attention-gfx950.sh`,
    lines: [
      "OPTIMIZATION STACK",
      "OPTIMIZATION [native-fp8-transpose-mfma]: Stage one packed E4M3 key tile in LDS, issue four gfx950 B8 transpose reads, and compute QK with one native 16x16x128 FP8 MFMA.",
      "IMPACT [native-fp8-transpose-mfma]: Final production median 22.320 us with HSACO 6ed1c00a...; isolated latency contribution is unavailable because no exact non-MFMA artifact was admitted.",
      "OPTIMIZATION [sparse-reciprocal-reuse]: Replace three denominator divisions per output lane with one reciprocal and a weighted numerator.",
      "IMPACT [sparse-reciprocal-reuse]: Preliminary GPU3 median 21,240 ns -> 21,200 ns, 0.19% lower; instructions 2,015 -> 1,999 while 80 VGPRs, 34 SGPRs, and 2,048 B LDS are unchanged.",
      "OPTIMIZATION [sparse-scalar-selection]: Materialize the bounded 128-score selection as a scalar loop and statement-selection path.",
      "IMPACT [sparse-scalar-selection]: Rejected because the V1 compiler does not support this bounded-loop and statement-selection combination.",
      "OPTIMIZATION [sparse-lds-double-buffer]: Add a second LDS buffer and prefetch the next key tile while the current tile executes.",
      "IMPACT [sparse-lds-double-buffer]: Inapplicable because K=128 is exactly one native MFMA tile; a second 2,048 B stage would duplicate the same data and add a barrier.",
      "PRELIMINARY ABLATION PROTOCOL: physical GPU 3; one process; 100 warmups; 5 blocks x 100 samples; 10 block-rewarm dispatches. Final production values below remain pinned and unchanged.",
      "KERNEL: gfx950_content_sparse_attention",
      "Optimization stack: rank a fixed content domain, stage packed E4M3 fragments in LDS, use four gfx950 transpose reads, issue one native FP8 MFMA for QK, and evaluate softmax/PV only over the three selected IDs.",
      "Preliminary reciprocal comparison: canonical p5/p95 21,080/21,560 ns; reciprocal p5/p95 21,000/21,480 ns. The ranges overlap, so no promotion or fastest conclusion is admitted.",
      "Measured production candidate: median 22.320 us; bootstrap 95% CI [22.320, 22.360] us; p5/p95 22.160/22.640 us; HSACO 6ed1c00a4509c0ed7d277e78dcc81c1bfd831da7dfc09f3091d9363ce520cd54.",
      "This candidate-only measurement admits no baseline, speedup, fastest-kernel, or state-of-the-art conclusion.",
      "THEORETICAL RESOURCE FLOOR",
      "max(4,492 B / 8 TB/s, 65,536 FP8 MFMA FLOPs / 4.6 PFLOP/s, 169 logical scalar ops / 144.2 TFLOP/s) = 0.5615 ns; reciprocal/floor = 37,756x.",
      "WORKLOAD BOUNDS: 16 tokens, head dimension 128, 16 value channels, top two four-token blocks, then top three token IDs.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because the exact QK workload contains one native K tile followed by serial selection and softmax.",
      "LDS MULTI-BUFFER ASSESSMENT: Rejected because a second LDS stage duplicates the only 2,048 B key tile and adds synchronization.",
      "TILE SHAPE ASSESSMENT: Retained the exact native 16x16x128 MFMA tile; any additional K tile changes the fixed workload.",
      "The floor excludes the bounded data-dependent selection network, four exponentials, dispatch, cache, and serial top-k latency.",
      "",
      "ADMITTED COMPARATOR RESULT",
      "None. ISA presence and an exact CPU-oracle pass do not establish performance or state of the art.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-compressed-hybrid-attention",
    evidencePath: `${finalAdvancedEvidencePath}; examples/gfx950_advanced_attention/run-compressed-hybrid-attention-gfx950.sh`,
    lines: [
      "OPTIMIZATION STACK",
      "OPTIMIZATION [hybrid-fused-native-path]: Keep compressed-global and four-token local branches in one launch around one native FP8 MFMA.",
      "IMPACT [hybrid-fused-native-path]: Final production median 22.800 us with HSACO 6c6addf0...; fusion contribution is unavailable because no exact independent unfused Rust artifact was admitted.",
      "OPTIMIZATION [hybrid-reciprocal-reuse]: Reuse one reciprocal across four local weights and one reciprocal across three compressed-global weights.",
      "IMPACT [hybrid-reciprocal-reuse]: Preliminary GPU3 median 21,600 ns -> 21,441 ns, 0.74% lower; instructions 1,948 -> 1,887 while 80 VGPRs, 30 SGPRs, and 2,048 B LDS are unchanged.",
      "OPTIMIZATION [hybrid-scalar-seven-score]: Replace the native score path with a scalar seven-score branch implementation.",
      "IMPACT [hybrid-scalar-seven-score]: Rejected because the V1 compiler does not support the required bounded scalar control-flow form.",
      "OPTIMIZATION [hybrid-split-fusion]: Materialize local and compressed-global branch outputs in separate dispatches.",
      "IMPACT [hybrid-split-fusion]: Inapplicable because additional intermediate buffers and dispatches change the exact ABI and compulsory-traffic contract.",
      "OPTIMIZATION [hybrid-lds-double-buffer]: Ping-pong two LDS key stages around the FP8 MFMA.",
      "IMPACT [hybrid-lds-double-buffer]: Inapplicable because K=128 supplies only one native MFMA tile, so no next tile exists to overlap.",
      "PRELIMINARY ABLATION PROTOCOL: physical GPU 3; one process; 100 warmups; 5 blocks x 100 samples; 10 block-rewarm dispatches. Final production values below remain pinned and unchanged.",
      "KERNEL: gfx950_compressed_hybrid_attention",
      "Optimization stack: stage packed E4M3 fragments once, use four gfx950 transpose reads plus one native FP8 MFMA, retain compressed and local branches in one launch, and fuse their outputs before the final store.",
      "Preliminary reciprocal comparison: canonical p5/p95 21,400/21,960 ns; reciprocal p5/p95 21,240/21,761 ns. The ranges overlap, so no promotion or fastest conclusion is admitted.",
      "Measured production candidate: median 22.800 us; bootstrap 95% CI [22.800, 22.801] us; p5/p95 22.600/23.160 us; HSACO 6c6addf04c745ad6560e45d2896725adbb8d87952cd49c6f710fde6e5011d823.",
      "This candidate-only measurement admits no baseline, speedup, fastest-kernel, or state-of-the-art conclusion.",
      "WORKLOAD BOUNDS: 16 tokens, head dimension 128, 16 value channels, three compressed four-token blocks, and tokens 12-15 as the local window.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because the exact QK work has one native K tile and both branches consume its completed scores.",
      "LDS MULTI-BUFFER ASSESSMENT: Rejected because no second K tile exists for a second 2,048 B stage.",
      "TILE SHAPE ASSESSMENT: Retained the exact native 16x16x128 MFMA tile; the scalar seven-score alternative was compiler-rejected.",
      "THEORETICAL RESOURCE FLOOR",
      "max(4,480 B / 8 TB/s, 65,536 FP8 MFMA FLOPs / 4.6 PFLOP/s, 529 logical scalar ops / 144.2 TFLOP/s) = 0.5600 ns; reciprocal/floor = 38,288x.",
      "The floor excludes eight exponentials, five maximum comparisons, dispatch, and the serial compression/fusion dependency chain.",
      "",
      "ADMITTED COMPARATOR RESULT",
      "None. A fused source shape is not itself evidence that fusion improved latency.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-attnres-gr-mhc",
    evidencePath: `${finalAdvancedEvidencePath}; examples/gfx950_advanced_attention/performance-mhc-sinkhorn-v1.json`,
    lines: [
      "OPTIMIZATION STACK",
      "OPTIMIZATION [attnres-explicit-unroll]: Replace the bounded four-depth loop with explicit logits, weights, and reuse.",
      "IMPACT [attnres-explicit-unroll]: Preliminary GPU3 median 3,280 ns -> 3,320 ns, a 1.22% regression; instructions 403 -> 402 while 23 VGPRs, 22 SGPRs, and 0 B LDS are unchanged.",
      "OPTIMIZATION [four-branch-explicit-unroll]: Replace the bounded four-branch loop with four explicit sigmoid-gated branches.",
      "IMPACT [four-branch-explicit-unroll]: Preliminary GPU3 median 3,360 ns -> 3,320 ns, 1.19% lower; both artifacts have 425 instructions, 24 VGPRs, 26 SGPRs, and 0 B LDS, and overlapping ranges prevent promotion.",
      "OPTIMIZATION [mhc-distributed-wave16]: Assign the rotated 4x4 mixing matrix across four contiguous wave16 groups instead of evaluating the full matrix per lane.",
      "IMPACT [mhc-distributed-wave16]: Final paired median 7.160 us -> 5.040 us, a 1.432x speedup and 30.1676% latency reduction; instructions 1,750 -> 457, VGPRs 34 -> 12, and SGPRs 34 -> 22.",
      "OPTIMIZATION [mhc-reciprocal-reuse]: Reduce each four-element row in its subgroup and reuse one reciprocal for its four normalized elements.",
      "IMPACT [mhc-reciprocal-reuse]: Expanded divides and v_rcp_f32 instructions each fell from 96 to 6, or 93.75%; independent latency contribution is unavailable because it was timed only inside the combined rewrite.",
      "OPTIMIZATION [mhc-column-broadcasts]: Replace divergent column selection with four bounded lane broadcasts and reuse the final row weights.",
      "IMPACT [mhc-column-broadcasts]: Scalar branches fell from 8 to 2 while 22 ds_bpermute_b32 instructions were added; independent latency contribution is unavailable because no exact broadcast-only artifact was admitted.",
      "OPTIMIZATION [mixing-lds-staging]: Stage each four-element AttnRes, gated-residual, or mHC reduction through LDS.",
      "IMPACT [mixing-lds-staging]: Rejected because each fixed four-element reduction fits in registers; LDS would add stores, loads, and barriers without an independent next tile.",
      "PRELIMINARY ATTENTION ABLATIONS: physical GPU 3; one process; 100 warmups; 5 blocks x 100 samples; 10 block-rewarm dispatches. The mHC paired result below remains the final admitted comparison.",
      "KERNEL: gfx950_mhc_sinkhorn_mix",
      "1. Assign one rotated 4x4 mixing-matrix element to each lane in four contiguous wave16 groups.",
      "2. Reduce each four-element row inside its subgroup and reuse one reciprocal for all four elements.",
      "3. Replace divergent column selection with four verifier-bounded lane broadcasts.",
      "4. Broadcast final row weights once and reuse them across the four stream loads.",
      "",
      "CONTRIBUTION BREAKDOWN",
      "KERNEL: gfx950_attnres_aggregate",
      "AttnRes aggregate final candidate: median 5.040 us; bootstrap 95% CI [5.000, 5.040] us; p5/p95 4.480/5.202 us; HSACO f3ab4ebd7b8f2310918eada0d8b90efd57c281914bbac91499040417f5c4a2e6. No baseline comparator or theoretical ledger was admitted, so contribution and floor remain unavailable.",
      "KERNEL: gfx950_four_branch_residual",
      "Four-branch residual final candidate: median 5.040 us; bootstrap 95% CI [5.000, 5.040] us; p5/p95 4.640/5.160 us; HSACO 190ce48f1172f15b3827b1220ad6ee190087ad4be52892946eff26cfea168ec0. No baseline comparator or theoretical ledger was admitted, so contribution and floor remain unavailable.",
      "mHC/Sinkhorn measured ablation:",
      "Distributed lanes: v_exp_f32 16 -> 1 (-93.75%); global dword loads 12 -> 5 (-58.33%).",
      "Row reduction plus reciprocal reuse: expanded divides 96 -> 6 and v_rcp_f32 96 -> 6 (-93.75% each).",
      "Bounded column broadcasts: scalar branches 8 -> 2 (-75%); adds 22 ds_bpermute_b32 instructions.",
      "Combined: instructions 1,750 -> 457 (-73.89%); SGPRs 34 -> 22; VGPRs 34 -> 12.",
      "Only the combined rewrite was timed. Overlapping static deltas are not additive marginal latency speedups.",
      "",
      "WORKLOAD BOUNDS: 16 channels; four AttnRes depths, four gated residual branches, four mHC streams, and three ordered Sinkhorn iterations.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because max, normalization, gating, and each Sinkhorn iteration consume the preceding reduction result.",
      "LDS MULTI-BUFFER ASSESSMENT: Rejected because every four-element working set is register-resident and has no independent next tile.",
      "TILE SHAPE ASSESSMENT: Retained one Wave64 over the exact 4x16 and 4x4 shapes; explicit AttnRes/four-branch forms did not establish a promotable gain.",
      "MI350X PROTOCOL",
      "Host: smci350-rck-g03-b19-03; physical GPU 6; gfx950:xnack-; ROCm 7.2.1",
      "Timer: hsa_amd_profiling_get_dispatch_time with one persistent profiled queue/executable per process",
      "Five fresh processes per variant in alternating AB/BA order",
      "Per process: 1,000 warmups; 30 blocks x 100 samples; 20 untimed block-rewarm dispatches",
      "15,000 paired samples; 10,000 bootstrap repetitions; seed 950",
      "Correctness: independent CPU mHC/Sinkhorn oracle plus output guard canaries; candidate max abs error 5.960464478e-8 <= 3e-3.",
      "",
      "MEASURED RESULT",
      "Final current-production mHC observation: median 5.000 us; bootstrap 95% CI [5.000, 5.000] us; p5/p95 4.920/5.160 us; HSACO f463b05e53db65c4e9ea73a0d33ce1398c85bcc8b5aab64788fdeb7858c9fdcc. This candidate-only campaign adds no new comparator or fastest claim.",
      "Prior paired ablation baseline HSACO 0a42de9c...: median 7.160 us; bootstrap 95% CI [7.160, 7.160] us.",
      "Distributed-wave16 HSACO f463b05e...: median 5.040 us; bootstrap 95% CI [5.000, 5.040] us.",
      "Paired median speedup 1.432x; bootstrap 95% CI [1.4318568, 1.432]; latency reduction 30.1676%.",
      "The final candidate-only campaign measured AttnRes at 5.040 us [5.000, 5.040] and four-branch residual at 5.040 us [5.000, 5.040]; it admitted no baseline comparator for either.",
      "",
      "THEORETICAL RESOURCE FLOORS",
      "Unique bytes = 64 B logits + 256 B streams + 256 B output = 576 B.",
      "Logical arithmetic = 616 FP32 algebraic ops plus 16 exponentials.",
      "AttnRes: max(576 B / 8 TB/s, 288 FP32 ops / 144.2 TFLOP/s) = 0.072 ns; preliminary canonical/floor = 45,556x.",
      "Four-branch: max(640 B / 8 TB/s, 320 FP32 ops / 144.2 TFLOP/s) = 0.080 ns; preliminary explicit/floor = 41,500x.",
      "AttnRes has 64 exponentials; four-branch has 64 exponentials. Their serial latency is outside the throughput floor.",
      "mHC ledger:",
      "max(576 B / 8 TB/s, 616 ops / 144.2 TFLOP/s) = max(0.072 ns, 0.00427 ns) = 0.072 ns.",
      "Candidate/resource floor = 5,040 ns / 0.072 ns = 70,000x.",
      "This strict whole-device floor omits dispatch latency and an exponential dependency-throughput bound.",
      "",
      "ADMITTED COMPARATOR RESULT",
      "The optimized artifact is fastest among the two exact-semantics Rust mHC artifacts admitted by this campaign.",
      "No performance comparator or fastest claim is admitted for AttnRes aggregate or four-branch residual.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-speculative-mtp-verification",
    evidencePath: `${finalAdvancedEvidencePath}; examples/gfx950_advanced_systems/optimization-evidence-v1.json`,
    lines: [
      "OPTIMIZATION STACK",
      "OPTIMIZATION [acceptance-reuse]: Compute each candidate accepted prefix once, broadcast it to eight state elements, and remove the duplicate acceptance path.",
      "IMPACT [acceptance-reuse]: Median 8.00 us -> 5.68 us, saving 2.32 us for a 1.408x speedup; global instructions 16 -> 10, VALU 77 -> 62, VGPRs 27 -> 17, and SGPRs 66 -> 62.",
      "KERNEL: gfx950_speculative_transaction_v1",
      "Compute each candidate's accepted prefix once, broadcast it to the eight state elements, and remove the duplicate acceptance path.",
      "Static contribution: global instructions 16 -> 10; VALU 77 -> 62; VGPRs 27 -> 17; SGPRs 66 -> 62.",
      "Final current-production observation: median 5.800 us; bootstrap 95% CI [5.760, 5.800] us; p5/p95 5.680/5.880 us; HSACO 5074044f3b46e0b04d24b066cfc23877df312d093dec151c75e3d126d36bbfde. This candidate-only campaign adds no new comparator or fastest claim.",
      "Prior paired-ablation contribution: 8.00 us [8.00, 8.04] -> 5.68 us [5.68, 5.68], saving 2.32 us; 1.408x.",
      "This is one fused rewrite, so no independent per-stage latency attribution is claimed.",
      "",
      "WORKLOAD BOUNDS: eight candidates, four draft steps, and eight state elements; state deltas commit only when all four steps pass.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because every accepted-prefix decision consumes the preceding draft-step predicate.",
      "LDS MULTI-BUFFER ASSESSMENT: Inapplicable because the fixed state is register-resident and has no repeated global-memory tile stage.",
      "TILE SHAPE ASSESSMENT: Retained one Wave64 over the exact eight-candidate by four-step transaction shape.",
      ...finalCandidateProtocol,
      "",
      "THEORETICAL RESOURCE FLOOR",
      "Logical payload = 896 B; counted work = 64 committed-state FP32 adds.",
      "max(896 B / 8 TB/s, 64 ops / 144.2 TFLOP/s) = 0.112 ns.",
      "Retained/resource floor = 5,680 ns / 0.112 ns = 50,714x.",
      "The floor counts proposed deltas read by the two committed candidates and excludes dispatch/cache effects.",
      "",
      "ADMITTED COMPARATOR RESULT",
      "The retained artifact is fastest among the exact baseline and acceptance-reuse artifacts in this campaign.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-ngram-embedding-gather",
    evidencePath: `${finalAdvancedEvidencePath}; examples/gfx950_advanced_systems/optimization-evidence-v1.json`,
    lines: [
      "OPTIMIZATION STACK",
      "OPTIMIZATION [hash-first-short-circuit]: Short-circuit each probe on hash mismatch before comparing the full three-token key.",
      "IMPACT [hash-first-short-circuit]: Rejected because median latency rose from 8.52 us to 10.68 us, a 2.16 us or 25.35% regression; the branchless 878-instruction path was retained.",
      "KERNEL: gfx950_qwen_ngram_gather_v1",
      "Tested optimization: short-circuit each probe on hash mismatch before the full three-token key comparison.",
      "Final current-production observation: median 8.640 us; bootstrap 95% CI [8.640, 8.640] us; p5/p95 8.560/8.800 us; HSACO 870afb85c86525288e1695d9764fd84180b62d20388c2678ef96ab318987699b. This candidate-only campaign adds no new comparator or fastest claim.",
      "Prior paired-ablation result: rejected. Hash-first median 10.68 us [10.64, 10.68] versus branchless baseline 8.52 us [8.52, 8.56].",
      "Negative contribution: +2.16 us, or 25.35% slower relative to the retained 8.52 us path.",
      "Retained design: branchless full-key probe; 878 instructions, 251 VALU, 66 global, 33 branches, 22 VGPRs, 34 SGPRs.",
      "",
      ...finalCandidateProtocol,
      "WORKLOAD BOUNDS: eight queries, three tokens per N-gram, 16 table slots, and one integer result per query.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because every bounded probe address and exact-key check depends on the preceding table-probe result.",
      "LDS MULTI-BUFFER ASSESSMENT: Inapplicable because the 16-slot table is a single bounded gather domain rather than a repeated staged tile.",
      "TILE SHAPE ASSESSMENT: Retained the exact eight-query, 16-slot branchless mapping; no differently shaped lookup was admitted.",
      "",
      "THEORETICAL RESOURCE FLOOR",
      "Logical payload = 576 B; hash and key comparisons are integer work and are not mapped to an FP32 peak.",
      "576 B / 8 TB/s = 0.072 ns; retained/resource floor = 8,520 ns / 0.072 ns = 118,333x.",
      "The whole-device bandwidth floor is not a single-wave latency prediction.",
      "",
      "ADMITTED COMPARATOR RESULT",
      "The retained branchless artifact is fastest among the exact branchless and hash-first variants in this campaign.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-muon-optimizer",
    evidencePath: `${finalAdvancedEvidencePath}; examples/gfx950_advanced_systems/optimization-evidence-v1.json`,
    lines: [
      "OPTIMIZATION STACK",
      "OPTIMIZATION [stage-wave64-copy]: Retain the existing one-Wave64 exact gradient-shard copy.",
      "IMPACT [stage-wave64-copy]: The exact comparison tied at 5.00 us, a 0 ns and 1.00x contribution, with 282 instructions.",
      "OPTIMIZATION [muon-distributed-wave]: Assign one 4x4 matrix element per lane and exchange reductions and broadcasts across Wave64.",
      "IMPACT [muon-distributed-wave]: Median 5.72 us -> 5.04 us, saving 0.68 us for a 1.135x speedup; instructions 1,360 -> 593, VALU 969 -> 160, branches 21 -> 3, VGPRs 62 -> 19, and SGPRs 58 -> 22.",
      "KERNEL: gfx950_stage_gradient_shard_v1",
      "Stage final current-production observations: stage 0 median 3.320 us [3.320, 3.320], p5/p95 3.320/4.160 us; stage 1 median 3.320 us [3.320, 3.320], p5/p95 3.320/4.280 us; shared HSACO ac52b38973af23d63dbb05f6edd0ceea5caa92f1f331318d95fe7d62d5b251ce. This candidate-only campaign adds no new comparator or fastest claim.",
      "Prior stage comparison: retain the existing one-Wave64 exact copy; 5.00 us -> 5.00 us, 0 ns, 1.00x; 282 instructions.",
      "KERNEL: gfx950_muon_update_4x4_v1",
      "Muon: assign one 4x4 matrix element per lane and exchange reductions/broadcasts across Wave64.",
      "Muon static contribution: instructions 1,360 -> 593; VALU 969 -> 160; branches 21 -> 3; VGPRs 62 -> 19; SGPRs 58 -> 22.",
      "The distributed form adds 86 ds_bpermute instructions while removing redundant per-lane matrix evaluation.",
      "Muon final current-production observation: median 5.000 us; bootstrap 95% CI [5.000, 5.000] us; p5/p95 4.680/5.360 us; HSACO bb6e61181e05244a71b6475bcc34a6a0c62d94147bbe27304287f71d8181fe5d. This candidate-only campaign adds no new comparator or fastest claim.",
      "Prior paired-ablation contribution: 5.72 us [5.70, 5.76] -> 5.04 us [5.00, 5.04], saving 0.68 us; 1.135x.",
      "Distribution and exchange were timed together; their overlapping static effects are not separate latency contributions.",
      "",
      ...finalCandidateProtocol,
      "",
      "WORKLOAD BOUNDS: two rank-ordered gradient shards reduce into one 4x4 FP32 matrix, followed by five polar iterations and learning-rate scale 0.05.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because each polar iteration consumes the preceding 4x4 iterate.",
      "LDS MULTI-BUFFER ASSESSMENT: Inapplicable because the complete 4x4 working matrix remains in registers and Wave64 exchanges.",
      "TILE SHAPE ASSESSMENT: Retained the exact 4x4 one-element-per-lane map; larger matrix tiles are differently shaped implementations.",
      "THEORETICAL RESOURCE FLOORS",
      "Stage: 128 B / 8 TB/s = 0.016 ns; retained/floor = 312,500x.",
      "Muon: max(196 B / 8 TB/s, 1,649 FP32 ops / 144.2 TFLOP/s) = 0.0245 ns.",
      "Muon retained/resource floor = 5,040 ns / 0.0245 ns = 205,714x.",
      "These optimistic whole-device floors exclude dispatch, dependencies, cache effects, and host-staged reduction time.",
      "",
      "ADMITTED COMPARATOR RESULT",
      "The distributed Muon artifact is fastest among the two exact Muon artifacts admitted by this campaign; stage ties its baseline.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-gpt-oss-120b-megakernel",
    evidencePath: "perf-evidence/gpt-oss-layer-tile-evidence-v1.json",
    lines: [
      "OPTIMIZATION STACK",
      "OPTIMIZATION [parallel-router]: Assign two of 128 expert logits to each Wave64 lane and merge a stable top-4 through bounded broadcasts.",
      "IMPACT [parallel-router]: Latency contribution is unavailable because no exact independent router-only artifact was admitted.",
      "OPTIMIZATION [fused-attention]: Feed four BF16 MFMAs into sink-aware softmax and value accumulation without materializing a probability matrix.",
      "IMPACT [fused-attention]: Latency contribution is unavailable because no exact independent attention-materialization baseline was admitted.",
      "OPTIMIZATION [sequential-mxfp4-fragments]: Scale and consume each MXFP4 result before constructing the next accumulator fragment.",
      "IMPACT [sequential-mxfp4-fragments]: Preliminary single-process smoke median 1.240483 ms -> 1.065242 ms, 14.1268% lower, while VGPRs fell from 352 to 308.",
      "OPTIMIZATION [disjoint-final-stores]: Commit attention, selected-expert output, and packed route IDs from one dispatch using disjoint stores.",
      "IMPACT [disjoint-final-stores]: Independent latency contribution is unavailable because no exact store-only comparator exists.",
      "OPTIMIZATION [bf16-router-mfma]: Replace the useful batch-1 router row with padded BF16 MFMA work.",
      "IMPACT [bf16-router-mfma]: Rejected because median latency was 2.174 ms, 104.1% slower than the optimized smoke result.",
      "KERNEL: gfx950_gpt_oss_120b_decode_megakernel_v1",
      "1. Parallel router: each Wave64 lane computes two of 128 expert logits, then bounded broadcasts merge a stable top-4 with lower expert ID winning ties.",
      "2. Fused attention: four BF16 MFMAs feed sink-aware softmax and direct value accumulation without materializing a probability matrix.",
      "3. Sequential MXFP4 fragments: scale and consume each of four block results before constructing the next accumulator fragment.",
      "4. Disjoint final stores: one dispatch commits attention, selected-expert output, and packed top-4 route IDs.",
      "",
      "Contribution breakdown",
      "Preliminary held-fragment fused baseline: 352 VGPRs, 1.240483 ms single-process smoke median.",
      "Preliminary sequential-fragment fused candidate: 308 VGPRs, 1.065242 ms single-process smoke median.",
      "Preliminary combined fragment-lifetime contribution: 44 fewer VGPRs and 14.1268% lower smoke median.",
      "Rejected BF16-MFMA router experiment: 2.174 ms, 104.1% slower than the optimized smoke result because one useful batch-1 row does not amortize padded matrix work and operand movement.",
      "The fragment rewrite is the only isolated positive timing attribution. Dispatch fusion and the router/attention/expert stages were not timed as additive marginal optimizations.",
      "",
      "MI350X PROTOCOL",
      "Host: smci350-rck-g03-b19-03; physical GPU 6; gfx950:xnack-; ROCm 7.2.1",
      "Timer: ROCr HSA dispatch timestamps; five fresh processes per variant in alternating AB/BA order",
      "WORKLOAD BOUNDS: one batch-1 layer tile with 128 router experts, four BF16 attention MFMAs, four executed MXFP4 expert MFMAs, and one Wave64 workgroup.",
      "SOFTWARE PIPELINE ASSESSMENT: Rejected because the fused one-wave router, attention, selected-expert, and store chain has serial dependencies and no independent next tile.",
      "LDS MULTI-BUFFER ASSESSMENT: Inapplicable because the admitted tile consumes fragments directly and exposes no repeated LDS-backed K stage.",
      "TILE SHAPE ASSESSMENT: Retained the exact batch-1 layer tile; the padded BF16 router tile was measured and rejected.",
      "Per process: 1,000 warmups; 30 blocks x 100 samples; 20 untimed block rewarms",
      "Samples: 15,000 per variant; hierarchical bootstrap 95% confidence intervals",
      "Correctness: independent CPU router, sink-softmax attention, selected-expert, packed-ID, immutable-input, and canary checks",
      "Commands: bash examples/gfx950_gpt_oss_decode/run-gfx950.sh; bash examples/gfx950_gpt_oss_decode/run-unfused-gfx950.sh; bash perf-evidence/run-gpt-oss-performance.sh",
      "Campaign commit: c1383e97db732f9f1ff8105f10d5c2b5971143e1; tree 42385e6464ca40318fc70ae104845d3997844140; final integrated Rust and exact-comparator artifacts passed their correctness gates.",
      "",
      "MEASURED RESULT",
      "Production Rust fused: median 1.064644 ms; bootstrap 95% CI [1.064483, 1.064844] ms; p5/p95 1.059803/1.069283 ms; HSACO 066056a1fb2228c9043474d1746a7555ac31c0ca559d678844dc9e89d601f212.",
      "Exact unfused HIP router + attention + expert: median 0.780362 ms; bootstrap 95% CI [0.780243, 0.780482] ms; p5/p95 0.778162/0.783123 ms; HSACO fb18b8bba5b598aa36dc2b94850dfc8724cfeae2d4cbbc26d0235f60d873c347.",
      "The exact unfused sequence is 0.732979x the fused duration; fused is 1.3643x slower.",
      "Eliminating two dispatches did not offset the fused one-wave dependency chain and register pressure.",
      "",
      "THEORETICAL RESOURCE FLOOR",
      "Unique compulsory bytes = 1,509,972 B.",
      "Counted arithmetic = 745,472 FP32 FLOPs, 32,768 executed BF16 MFMA FLOPs, and 262,144 executed MXFP4 MFMA FLOPs; only 4,096 MXFP4 FLOPs are useful for the non-padding batch-1 row.",
      "HBM floor = 1,509,972 B / 8 TB/s = 188.7465 ns; FP32 floor = 745,472 / 144.2 TFLOP/s = 5.1697 ns; MXFP4 floor = 262,144 / 9.2 PFLOP/s = 0.0285 ns.",
      "T_resource = max(188.7465, 5.1697, 0.0285) ns = 188.7465 ns. Omitting an unavailable BF16 peak makes this deliberately optimistic.",
      "Fused/resource floor = 5,640.6x; exact comparator/resource floor = 4,134.4x.",
      "This whole-device throughput floor excludes dispatch, scalar and transcendental latency, dependencies, cache behavior, and the fact that the profile launches one Wave64 workgroup.",
      "",
      "ADMITTED COMPARATOR RESULT",
      "The fused kernel lost to the exact admitted three-dispatch comparator for this fixed batch-1 tile.",
      "Fastest claim: not claimed.",
      "State-of-the-art claim: not claimed.",
      ...boundedClaim,
    ],
  },
];

export const advancedPerformanceLessonIds = records.map(
  (record) => record.lessonId,
);

export function advancedPerformanceTabFor(
  lessonId: string,
): CodeTab | undefined {
  const record = records.find((candidate) => candidate.lessonId === lessonId);
  if (!record) return undefined;
  return {
    kind: "performance",
    label: "Performance",
    language: "text",
    code: [
      "FE2O3 GFX950 BOUNDED PERFORMANCE EVIDENCE",
      `Evidence source: ${record.evidencePath}`,
      "",
      ...record.lines,
    ].join("\n"),
    explanatory: true,
    notice:
      "Bounded MI350X ablation evidence. Comparator scope, protocol limits, correctness gates, and resource-floor assumptions are part of the record; no universal state-of-the-art claim is made.",
  };
}
