import type { CodeTab } from "./model";

interface AdvancedPerformanceRecord {
  lessonId: string;
  evidencePath: string;
  lines: string[];
}

const boundedClaim = [
  "CLAIM BOUNDARY",
  "These are fixed-shape MI350X measurements, not universal state-of-the-art claims.",
  "State-of-the-art claim: not claimed; fastest statements are limited to admitted variants.",
  "A fastest statement applies only to the exact admitted artifacts and protocol named below.",
  "Framework, full-model, multi-workgroup, and differently shaped implementations are not comparable here.",
  "The resource floor is an optimistic cold-HBM logical-payload roofline normalization, not a lower bound for the warmed-cache timing campaign.",
  "It grants the single workgroup all whole-device bandwidth and peak compute across 256 CUs, and excludes dispatch, cache, occupancy, issue, and dependency-chain limits.",
];

const evidence = "perf-evidence/gfx950-advanced-ablation-evidence-v1.json";
const compatibility = "perf-evidence/gfx950-integrated-compatibility-v1.json";
const boundInputs = "perf-evidence/mi350x-bound-inputs-v1.json";

const protocol = [
  "FINAL ABLATION PROTOCOL",
  "Host: smci350-rck-g03-b19-03; physical GPU 6; gfx950:xnack-; HIP_VISIBLE_DEVICES unset",
  "Measured source: da6c108d162bac8afd79e789ccf9b36ef8eb97a4; promoted production source: c766ca761c492c4cd188047a497664f6b2ade278",
  "One process per variant; 1,000 warmups; 30 blocks x 100 samples; 20 block-rewarm dispatches",
  "Timer: ROCr HSA dispatch timestamps; hierarchical bootstrap with 10,000 repetitions and seed 950",
  "Correctness: independent CPU reference, immutable-input checks, guard canaries, preflight dispatch, and post-block validation",
  "Campaign: 32 exact HSACOs, 35 timing series, 105,000 dispatch samples, and zero retained AMDGPU target directories",
];

const records: AdvancedPerformanceRecord[] = [
  {
    lessonId: "gfx950-kda-gdn-linear-attention",
    evidencePath:
      "examples/gfx950_advanced_attention/kda-mi350-performance-v1.json; examples/gfx950_advanced_attention/ablation-variants-v1.json; perf-evidence/mi350x-bound-inputs-v1.json",
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "OPTIMIZATION [decode-key-reuse]: Load the lane's key once and reuse it for both prediction and the rank-one state update.",
      "IMPACT [decode-key-reuse]: Five paired process medians improved 5,840 -> 4,720 ns, a 1.237288x median speedup with bootstrap 95% CI [1.168000, 1.269565] and a 19.1781% latency reduction.",
      "ISA [decode-key-reuse]: Global loads and Wave16 exchanges remain 5 and 8, while s_waitcnt falls 14 -> 11; SGPR/VGPR stay 58/14. The win is explicit reuse plus better dependency scheduling, not a claimed reduction in global-load count.",
      "OPTIMIZATION [prefill-c4-wy-ut]: Replace eight serial recurrence steps with two exact C=4 WY/UT chunks while carrying the 16x16 state in registers.",
      "IMPACT [prefill-c4-wy-ut]: Five paired process medians improved 15,080 -> 11,400 ns, a 1.322807x median speedup with bootstrap 95% CI [1.301038, 1.329825] and a 24.4032% latency reduction.",
      "ISA [prefill-c4-wy-ut]: Both forms issue 33 global loads and 3 global stores. WY/UT raises Wave16 exchanges 64 -> 192, waits 92 -> 135, and VGPRs 35 -> 85, yet wins because independent within-chunk reductions expose ILP and shorten the token-to-token dependency chain.",
      "OPTIMIZATION [workgroup-64-coarsening]: Assign four value columns to each of 64 lanes.",
      "IMPACT [workgroup-64-coarsening]: Correctness passed, but one-process medians regressed decode 4,720 -> 6,160 ns (+30.5085%) and prefill 11,400 -> 13,160 ns (+15.4386%); rejected because live state grew and the Wave16 reduction serialized.",
      "OPTIMIZATION [workgroup-128-pair-tile]: Pair two state elements per lane.",
      "IMPACT [workgroup-128-pair-tile]: Compiler-rejected because the verifier could not prove convergence around the early-exit reduction; no timing contribution is claimed.",
      "OPTIMIZATION [subgroup-load-coalescing]: Load selected inputs in producer lanes and broadcast them.",
      "IMPACT [subgroup-load-coalescing]: Compiler-rejected because conditional producers before subgroup broadcasts were not proven convergent; no timing contribution is claimed.",
      "OPTIMIZATION [lds-multibuffering]: Stage the state or a future key tile through ping-pong LDS buffers.",
      "IMPACT [lds-multibuffering]: Not applicable, contribution 0%, because the matrix state is register-resident and no repeated K tile exists; LDS would add stores, reloads, barriers, and no reuse.",
      "KERNEL: gfx950_kda_decode",
      "KERNEL: gfx950_kda_chunkwise_prefill",
      "WORKLOAD BOUNDS: FP32 B=1, H=1, K=16, V=16; normalized q/k; activated alpha/beta; decode T=1; prefill T=8 as two C=4 chunks; initial and final matrix state.",
      "SOFTWARE PIPELINE ASSESSMENT: The retained prefill uses a dependency-transforming C=4 WY/UT schedule to expose independent reductions. It is not a repeated global-memory tile pipeline, and no overlap contribution is claimed separately from the measured WY/UT ablation.",
      "LDS MULTI-BUFFER ASSESSMENT: Structurally inapplicable for this register-state, no-next-tile profile.",
      "TILE SHAPE ASSESSMENT: Retained 256 threads with one state element per lane; the correctness-passing 64-thread four-column tile regressed both kernels, and the 128-thread tile failed the proof gate.",
      "FINAL REPLICATED PROTOCOL",
      "Host: smci350-rck-g03-b19-03; physical GPU 6; gfx950:xnack-; ROCm 7.2.1; HIP_VISIBLE_DEVICES unset",
      "Exact timed source: cf8a766fe11a53b7bfa6d5678c903e877bb95d75; tree b9c09ca3ae2807cecd967d89ec3e4c4ca56ee633",
      "Five independent processes per variant; 1,000 warmups; 30 blocks x 100 dispatch samples; alternating variant order",
      "Statistic: median of five process medians; deterministic 20,000-resample bootstrap on process medians",
      "fe2o3 timer: individual ROCr HSA dispatch timestamps. FLA timer: torch HIP event over 100-call blocks. Both are device-side, but sampling granularity differs.",
      "Correctness: independent sequential f64 matrix-state reference; final state/output maxima <= 2.980232239e-8 across retained fe2o3 kernels.",
      "Environment disclosure: a foreign idle vLLM allocation was resident on physical GPU 6; no co-resident compute activity was observed.",
      "THEORETICAL RESOURCE FLOORS",
      "MI350X peak HBM bandwidth input: 8 TB/s from https://www.amd.com/en/products/accelerators/instinct/mi350/mi350x.html.",
      "Decode derivation: 3,332 B / 8 TB/s = 0.4165 ns; measured 4,720 ns is 11,332.5x the floor (0.008824% of bound).",
      "Prefill derivation: 6,176 B / 8 TB/s = 0.772 ns; measured 11,400 ns is 14,766.8x the floor (0.006772% of bound).",
      "The HBM-only floor is deliberately optimistic: it excludes launch and instruction latency, assumes peak whole-device bandwidth, and a single tiny head cannot saturate HBM. Dispatch and dependency latency dominate.",
      "ADMITTED COMPARATOR RESULT",
      "Official Flash Linear Attention fused_recurrent_kda commit 8e84ed4a6727be082c34a3855c60623fd11411e9 measured 39,345 ns decode and 39,113 ns T=8 recurrent prefill. fe2o3 is 8.335876x and 3.430941x faster, respectively.",
      "FLA chunk KDA only admits C=32 or C=64 and FlashKDA CUTLASS has a different BF16 K=V=128 contract, so neither is eligible for this exact C=4 FP32 comparison.",
      "Fastest claim: fastest measured eligible implementation for this exact shape and semantics. This is not a universal KDA state-of-the-art claim.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-advanced-moe",
    evidencePath: `${evidence}; ${compatibility}; ${boundInputs}; examples/gfx950_advanced_systems/ablation-variants-v1.json; examples/gfx950_advanced_systems/optimization-evidence-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "CURRENT PRODUCTION LAUNCH: WG256/grid4. Route and expert assign four independent Wave64 batches per workgroup (16 total); combine assigns one independent 256-element batch per workgroup (four total). No grid synchronization is required.",
      "CURRENT MI350 CORRECTNESS: route checked 512 expert IDs exact, 512 weights at max error 2.980232239e-8, 64 counts exact, and 2,048 dispatch entries exact; four expert plans each checked 4,096 outputs at max errors [9.536743164e-7, 4.768371582e-7, 0, 0]; combine checked 1,024 outputs at max error 0.",
      "CURRENT ALTERNATE COMPATIBILITY: expert-serial completed Rust extraction, HSACO/ISA generation, and HSA for four 4,096-output plans at max errors [9.536743164e-7, 4.768371582e-7, 0, 0]. combine-transposed failed closed before launch because projection could not prove its dynamic source-index addition cannot overflow. These are correctness outcomes, not timings.",
      "HISTORICAL PERFORMANCE BOUNDARY: Every latency, ISA delta, resource floor, and speedup below comes from the retained 2026-08-29 WG64/grid1 or WG256/grid1 campaign. No WG256/grid4 performance result is claimed.",
      "OPTIMIZATION [route-packed-reuse]: Compute each route once, broadcast stable top-2 choices, and reuse the packed route map.",
      "IMPACT [route-packed-reuse]: Historical grid1 production median 19,600 ns; three owner-only, per-record-broadcast, and u32-pack alternatives were rejected as noncanonical or compiler-invalid, so no fabricated marginal speedup is reported.",
      "OPTIMIZATION [expert-eager-ilp-schedule]: Load three independent activation/weight streams before issuing mixed FP4/FP8 MFMAs.",
      "IMPACT [expert-eager-ilp-schedule]: Historical one-wave serial -> eager medians were 38,520 -> 38,041 ns for rank 0 and 38,160 -> 37,720 ns for rank 1, reductions of 1.2435% and 1.1530%.",
      "OPTIMIZATION [expert-native-tile]: Use three gfx950 m16n16k128 mixed FP4/FP8 MFMAs in one Wave64.",
      "IMPACT [expert-native-tile]: Static ISA validation found exactly three scaled MFMAs with cbsz:4 and no scalar low-precision fallback; timing contribution is unavailable because no exact non-MFMA baseline was admitted.",
      "OPTIMIZATION [combine-ownership]: Keep exact 256-thread combine ownership rather than a transposed one-wave map.",
      "IMPACT [combine-ownership]: Historical grid1 canonical median 5,040 ns; the transpose alternative was compiler-rejected because its subgroup source lane was not statically bounded.",
      "KERNEL: gfx950_moe_route_fp4_t16_e4_k2_v1",
      "KERNEL: gfx950_moe_expert_rank_fp4_fp8_v1",
      "KERNEL: gfx950_combine_expert_ranks_v1",
      "WORKLOAD BOUNDS: 16 tokens, hidden 128, output 16, four routed experts, one shared expert, stable top-2 routing, and one fixed dispatch tile.",
      "SOFTWARE PIPELINE ASSESSMENT: No repeated software pipeline is used or implemented. The expert kernel uses eager instruction-level scheduling across three independent single-tile operand/MFMA streams; route and combine remain dependency-bound.",
      "LDS MULTI-BUFFER ASSESSMENT: Inapplicable because each expert stream has one K=128 tile and route/combine have no repeated producer-consumer tile.",
      "TILE SHAPE ASSESSMENT: Current route/expert preserve their Wave64-local algorithms inside four-wave workgroups, and combine preserves exact 256-thread ownership inside each independently based workgroup. Rejected historical maps did not pass the proof gate.",
      ...protocol,
      "THEORETICAL RESOURCE FLOORS",
      "Route derivation: max(4,880 B / 8 TB/s, 16,384 FP32 routing-dot ops / 144.2 TFLOP/s) = 0.610 ns.",
      "Expert derivation: max(9,472 B / 8 TB/s, 196,608 mixed FP4/FP8 MFMA ops / 4.6 PFLOP/s) = 1.184 ns.",
      "Combine derivation: max(3,072 B / 8 TB/s, 256 FP32 adds / 144.2 TFLOP/s) = 0.384 ns.",
      "Historical grid1 comparison: route floor 0.610 ns and measured/floor 32,131x; expert floor 1.184 ns and rank-0 measured/floor 32,129x; combine floor 0.384 ns and measured/floor 13,125x.",
      "ADMITTED COMPARATOR RESULT",
      "Eager expert scheduling is fastest among its two exact schedules. Route and combine expose the retained artifact plus documented compiler rejections.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-indexed-sparse-attention",
    evidencePath: `${evidence}; ${compatibility}; ${boundInputs}; examples/gfx950_advanced_attention/ablation-variants-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "OPTIMIZATION [sparse-native-mfma]: Stage one E4M3 key tile in 2,048 B LDS, issue four B8 transpose reads, then one m16n16k128 FP8 MFMA.",
      "IMPACT [sparse-native-mfma]: Static validation found exactly four ds_read_b64_tr_b8 instructions before one scaled FP8 MFMA and no scalar fallback; an exact scalar candidate was compiler-rejected.",
      "OPTIMIZATION [sparse-reciprocal]: Replace three normalized divisions with one reciprocal.",
      "IMPACT [sparse-reciprocal]: Measured 22,320 -> 22,361 ns; paired speedup 0.994662 with CI [0.994643, 0.996416], a 0.5367% regression, so it was rejected.",
      "OPTIMIZATION [sparse-lds-pingpong]: CANDIDATE ASSESSMENT (NOT IMPLEMENTED). Add a second 2,048 B LDS stage with prefetch distance one.",
      "IMPACT [sparse-lds-pingpong]: Structurally inapplicable; no source artifact was built or timed because K=128 is exactly one native tile, so a second stage duplicates data and adds synchronization.",
      "OPTIMIZATION [sparse-tile-tuning]: UNAVAILABLE (NOT IMPLEMENTED). Vary the native tile while preserving exact 16x16x128 work.",
      "IMPACT [sparse-tile-tuning]: Unavailable in the admitted API; no source artifact was built or timed because extra MFMAs change executed work.",
      "KERNEL: gfx950_content_sparse_attention",
      "WORKLOAD BOUNDS: 16 tokens, head dimension 128, 16 value channels, top two of four blocks, then top three token IDs.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because one QK tile feeds serial selection, softmax, and PV work.",
      "LDS MULTI-BUFFER ASSESSMENT: Structurally inapplicable; no candidate was built or timed because a second 2,048 B stage duplicates the only key tile.",
      "TILE SHAPE ASSESSMENT: Retained one exact m16n16k128 FP8 MFMA with four gfx950 transpose reads.",
      ...protocol,
      "THEORETICAL RESOURCE FLOOR",
      "Derivation: max(4,492 B / 8 TB/s, 65,536 FP8 FLOPs / 4.6 PFLOP/s, 169 scalar ops / 144.2 TFLOP/s) = 0.5615 ns; 22,320 ns is 39,751x the floor.",
      "ADMITTED COMPARATOR RESULT",
      "The retained division artifact is fastest among the two exact sparse arithmetic variants.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-compressed-hybrid-attention",
    evidencePath: `${evidence}; ${compatibility}; ${boundInputs}; examples/gfx950_advanced_attention/ablation-variants-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "OPTIMIZATION [hybrid-reciprocal]: Reuse one reciprocal across four local weights and one across three compressed-global weights.",
      "IMPACT [hybrid-reciprocal]: Measured 22,800 -> 22,560 ns, paired 1.007105x with CI [1.005378, 1.008818], a 0.7055% reduction; promoted into production.",
      "OPTIMIZATION [hybrid-promotion-proof]: Rebuild production and the renamed division baseline after promotion.",
      "IMPACT [hybrid-promotion-proof]: Measured 22,760 -> 22,640 ns over 500 samples, paired 1.005300x with CI [1.003534, 1.007080]; production reproduced winning HSACO 3cf9a73d... byte-for-byte.",
      "OPTIMIZATION [hybrid-fusion]: Keep local and compressed-global branches in one launch around one FP8 MFMA.",
      "IMPACT [hybrid-fusion]: Static fusion is retained, but isolated latency contribution is unavailable because materializing intermediates changes ABI and traffic.",
      "OPTIMIZATION [hybrid-lds-pingpong]: CANDIDATE ASSESSMENT (NOT IMPLEMENTED). Double-buffer key tiles around the FP8 MFMA.",
      "IMPACT [hybrid-lds-pingpong]: Structurally inapplicable; no source artifact was built or timed because K=128 supplies one native tile and no next tile exists to overlap.",
      "KERNEL: gfx950_compressed_hybrid_attention",
      "WORKLOAD BOUNDS: 16 tokens, head dimension 128, 16 value channels, three compressed blocks, and tokens 12-15 as the local window.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because the sole QK tile completes before both dependent branches.",
      "LDS MULTI-BUFFER ASSESSMENT: Structurally inapplicable; no candidate was built or timed because a second 2,048 B stage duplicates the only K tile.",
      "TILE SHAPE ASSESSMENT: Retained native m16n16k128 FP8; the scalar seven-score alternative was compiler-rejected.",
      ...protocol,
      "THEORETICAL RESOURCE FLOOR",
      "Derivation: max(4,480 B / 8 TB/s, 65,536 FP8 FLOPs / 4.6 PFLOP/s, 529 scalar ops / 144.2 TFLOP/s) = 0.5600 ns; 22,560 ns is 40,286x the floor.",
      "ADMITTED COMPARATOR RESULT",
      "Promoted reciprocal reuse is fastest among exact division and reciprocal artifacts in both final and post-promotion runs.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-attnres-gr-mhc",
    evidencePath: `${evidence}; ${compatibility}; ${boundInputs}; examples/gfx950_advanced_attention/ablation-variants-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "OPTIMIZATION [attnres-explicit]: Replace the four-depth loop with explicit logits and weights.",
      "IMPACT [attnres-explicit]: Measured 5,000 -> 5,040 ns; paired CI [0.992063, 1.0] includes parity, so it was not promoted.",
      "OPTIMIZATION [four-branch-explicit]: Replace the four-branch loop with explicit sigmoid-gated branches.",
      "IMPACT [four-branch-explicit]: Measured 5,000 -> 5,000 ns with paired CI [1.0, 1.0], an exact timing tie.",
      "OPTIMIZATION [mhc-wave16-distribution]: Distribute the rotated 4x4 matrix over four wave16 groups.",
      "IMPACT [mhc-wave16-distribution]: Measured scalar 7,240 -> distributed 5,000 ns, a 1.448x speedup and 30.9392% reduction; instructions 1,750 -> 457, VGPRs 34 -> 12, SGPRs 34 -> 22.",
      "OPTIMIZATION [mhc-reciprocal-reuse]: Reuse one reciprocal per four-element row normalization.",
      "IMPACT [mhc-reciprocal-reuse]: Static divides and reciprocal instructions fell 96 -> 6; independent latency is unavailable because distribution and reuse were timed together.",
      "OPTIMIZATION [mixing-lds-stage]: CANDIDATE ASSESSMENT (NOT IMPLEMENTED). Stage four-element reductions through LDS.",
      "IMPACT [mixing-lds-stage]: Structurally inapplicable; no source artifact was built or timed because four-element working sets fit in registers and LDS would add stores, loads, and barriers without reuse.",
      "KERNEL: gfx950_attnres_aggregate",
      "KERNEL: gfx950_four_branch_residual",
      "KERNEL: gfx950_mhc_sinkhorn_mix",
      "WORKLOAD BOUNDS: 16 channels; four AttnRes depths, four residual branches, four mHC streams, and three Sinkhorn iterations.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because every normalization and Sinkhorn iteration consumes the preceding reduction.",
      "LDS MULTI-BUFFER ASSESSMENT: Structurally inapplicable; no candidate was built or timed because four-element working sets are register-resident.",
      "TILE SHAPE ASSESSMENT: Retained one Wave64 over exact 4x16 and 4x4 shapes.",
      ...protocol,
      "THEORETICAL RESOURCE FLOORS",
      "AttnRes derivation: max(576 B / 8 TB/s, 288 counted FP32 algebraic ops / 144.2 TFLOP/s) = 0.072 ns; 64 logical exponentials are outside the published peak term; measured/floor 69,444x.",
      "Four-branch derivation: max(640 B / 8 TB/s, 320 counted FP32 algebraic ops / 144.2 TFLOP/s) = 0.080 ns; 64 logical exponentials are outside the published peak term; measured/floor 62,500x.",
      "mHC derivation: max(576 B / 8 TB/s, 616 counted FP32 algebraic ops / 144.2 TFLOP/s) = 0.072 ns; 16 logical exponentials are outside the published peak term; measured/floor 69,444x.",
      "ADMITTED COMPARATOR RESULT",
      "Distributed mHC is fastest among two exact artifacts; AttnRes explicit is indistinguishable and four-branch explicit ties.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-speculative-mtp-verification",
    evidencePath: `${evidence}; ${compatibility}; ${boundInputs}; examples/gfx950_advanced_systems/ablation-variants-v1.json; examples/gfx950_advanced_systems/optimization-evidence-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "CURRENT PRODUCTION LAUNCH: WG256/grid4 provides 16 independent Wave64 candidate batches with batch-local draft, target, score, base-state, delta, and output slices; no grid synchronization is required.",
      "CURRENT MI350 CORRECTNESS: 128 accepted lengths exact, 128 commit flags exact, and 1,024 output-state values with max error 1.192092896e-7.",
      "CURRENT ALTERNATE COMPATIBILITY: speculative-recompute-prefix completed Rust extraction, HSACO/ISA generation, and HSA with 128 accepted lengths exact, 128 commit flags exact, and 1,024 state values at max error 1.192092896e-7. No current timing contribution is claimed.",
      "HISTORICAL PERFORMANCE BOUNDARY: Latencies, speedups, ISA, and resource-floor ratios below are retained grid1 measurements, not measurements of the current WG256/grid4 source.",
      "OPTIMIZATION [prefix-broadcast]: Compute each accepted prefix once and broadcast it to eight state elements.",
      "IMPACT [prefix-broadcast]: Historical one-wave recompute 5,800 -> broadcast 5,760 ns, a 1.006944x speedup and 0.6897% reduction; distinct HSACOs prove the ablation exercised live code.",
      "OPTIMIZATION [transaction-fusion]: Validate four draft steps and commit state in one dispatch.",
      "IMPACT [transaction-fusion]: Measured production median 5,760 ns; an exact materialized baseline is unavailable because extra state buffers change the contract.",
      "OPTIMIZATION [transaction-prefetch]: CANDIDATE ASSESSMENT (NOT IMPLEMENTED). Prefetch the next candidate during the current prefix.",
      "IMPACT [transaction-prefetch]: Structurally inapplicable; no source artifact was built or timed because every prefix predicate consumes the preceding draft-step result.",
      "KERNEL: gfx950_speculative_transaction_v1",
      "WORKLOAD BOUNDS: eight candidates, four ordered draft steps, and eight state elements with all-or-nothing commit.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because draft predicates form a serial acceptance chain.",
      "LDS MULTI-BUFFER ASSESSMENT: Inapplicable because fixed state is register-resident with no repeated global tile.",
      "TILE SHAPE ASSESSMENT: Retained current WG256/grid4 mapping uses one eight-candidate by four-step transaction per wave and global Wave64 identity for 16 disjoint batches.",
      ...protocol,
      "THEORETICAL RESOURCE FLOOR",
      "Historical one-wave derivation: max(1,664 B / 8 TB/s, 256 FP32 ops / 144.2 TFLOP/s) = 0.208 ns; 5,760 ns is 27,692x the floor.",
      "ADMITTED COMPARATOR RESULT",
      "Prefix broadcast is fastest among exact broadcast and live-recomputation artifacts.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-ngram-embedding-gather",
    evidencePath: `${evidence}; ${compatibility}; ${boundInputs}; examples/gfx950_advanced_systems/ablation-variants-v1.json; examples/gfx950_advanced_systems/optimization-evidence-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "CURRENT PRODUCTION LAUNCH: WG256/grid4 provides 16 independent Wave64 query batches. Every wave uses its own query/table base and writes one disjoint eight-result slice.",
      "CURRENT MI350 CORRECTNESS: all 128 batch-major integer outputs matched the independent reference exactly under nonuniform per-batch inputs.",
      "CURRENT ALTERNATE COMPATIBILITY: ngram-reverse-probe completed Rust extraction, HSACO/ISA generation, and HSA with all 128 outputs exact. No current timing contribution is claimed.",
      "HISTORICAL PERFORMANCE BOUNDARY: Latencies, speedups, ISA, and resource-floor ratios below are retained one-wave/grid1 measurements, not measurements of the current WG256/grid4 source.",
      "OPTIMIZATION [ascending-probe]: Probe all 16 slots in ascending order, using a final-probe specialization while preserving exact priority and lower-slot tie resolution.",
      "IMPACT [ascending-probe]: Historical one-wave reverse 9,800 -> ascending 8,480 ns, a 1.15566x speedup and 13.4694% reduction.",
      "OPTIMIZATION [full-key-check]: Keep the exact three-token collision check.",
      "IMPACT [full-key-check]: Static exactness is retained; independent timing is unavailable because removing the key check changes semantics.",
      "OPTIMIZATION [table-lds-stage]: CANDIDATE ASSESSMENT (NOT IMPLEMENTED). Copy the 16-slot table into LDS before probing.",
      "IMPACT [table-lds-stage]: Structurally inapplicable per batch; no source artifact was built or timed because staging each wave's 16-slot table adds a copy and barrier without second-tile reuse.",
      "KERNEL: gfx950_qwen_ngram_gather_v1",
      "WORKLOAD BOUNDS: eight queries, three tokens per N-gram, 16 slots, and one integer result per query.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because each probe address and exact-key decision consumes the prior result.",
      "LDS MULTI-BUFFER ASSESSMENT: Inapplicable because the table is one bounded gather domain, not a repeated tile.",
      "TILE SHAPE ASSESSMENT: Retained current WG256/grid4 mapping uses eight queries over 16 slots per wave and derives 16 disjoint batches from global Wave64 identity; reverse order was measured historically and rejected.",
      ...protocol,
      "THEORETICAL RESOURCE FLOOR",
      "Historical one-wave derivation: 576 B / 8 TB/s = 0.072 ns; 8,480 ns is 117,778x the optimistic bandwidth floor.",
      "ADMITTED COMPARATOR RESULT",
      "Ascending probe order is fastest among exact ascending and reverse-order artifacts.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-muon-optimizer",
    evidencePath: `${evidence}; ${compatibility}; ${boundInputs}; examples/gfx950_advanced_systems/ablation-variants-v1.json; examples/gfx950_advanced_systems/optimization-evidence-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "CURRENT PRODUCTION LAUNCH: WG256/grid4 provides 16 independent Wave64 matrix batches for stage and Muon; every wave uses batch-local shard inputs and disjoint output/norm slices.",
      "CURRENT MI350 CORRECTNESS: two stage plans each checked 256 outputs at max error 0; Muon checked 256 updates at max error 7.450580597e-9 and 16 norms at max error 5.960464478e-8.",
      "CURRENT ALTERNATE COMPATIBILITY: muon-broadcast16 completed Rust extraction, HSACO/ISA generation, and HSA with 256 updates at max error 7.450580597e-9 and 16 exact norms. stage-tile4 failed closed before launch because its subgroup broadcast source lane was not statically bounded. These are correctness outcomes, not timings.",
      "HISTORICAL PERFORMANCE BOUNDARY: Latencies, speedups, ISA, and resource-floor ratios below are retained one-wave/grid1 measurements, not measurements of the current WG256/grid4 source.",
      "OPTIMIZATION [stage-wave64]: Copy each exact 4x4 gradient shard with one Wave64-local map.",
      "IMPACT [stage-wave64]: Historical one-wave stage medians are 5,000 ns; tile4 was compiler-rejected because its subgroup source lane was not statically bounded.",
      "OPTIMIZATION [muon-distribution]: Assign one 4x4 element per lane and exchange reductions instead of evaluating the full update per lane.",
      "IMPACT [muon-distribution]: A historical exploratory campaign (publishable_claim=false; 200 warmups; 5 blocks x 50 samples) observed exact scalar -> distributed at 5,720 -> 5,040 ns, a 1.135x speedup; instructions 1,360 -> 593, VALU 969 -> 160, VGPRs 62 -> 19, SGPRs 58 -> 22. This is context, not a final-protocol marginal attribution.",
      "OPTIMIZATION [muon-broadcast16]: Replace canonical reduction exchange with wave16 broadcasts.",
      "IMPACT [muon-broadcast16]: Final aggregate medians tied at 5,000 ns; a 0.8% paired movement is below robust marginal attribution, so canonical was retained.",
      "OPTIMIZATION [muon-iteration-pipeline]: CANDIDATE ASSESSMENT (NOT IMPLEMENTED). Overlap adjacent polar iterations or double-buffer the 4x4 iterate.",
      "IMPACT [muon-iteration-pipeline]: Structurally inapplicable; no source artifact was built or timed because each of five iterations consumes the preceding matrix and the working set stays in registers.",
      "KERNEL: gfx950_stage_gradient_shard_v1",
      "KERNEL: gfx950_muon_update_4x4_v1",
      "WORKLOAD BOUNDS: two gradient shards reduce into one 4x4 FP32 matrix, followed by five polar iterations.",
      "SOFTWARE PIPELINE ASSESSMENT: Inapplicable because each polar iteration consumes the preceding iterate.",
      "LDS MULTI-BUFFER ASSESSMENT: Inapplicable because the 4x4 matrix remains in registers and Wave64 exchanges.",
      "TILE SHAPE ASSESSMENT: Retained current WG256/grid4 mapping uses one element per active lane over each exact 4x4 matrix and derives 16 disjoint batches from global Wave64 identity; stage tile4 was compiler-rejected historically.",
      ...protocol,
      "THEORETICAL RESOURCE FLOORS",
      "Historical one-wave derivation: stage 128 B / 8 TB/s = 0.016 ns and measured/floor 312,500x; Muon max(196 B / 8 TB/s, 1,649 / 144.2 TFLOP/s) = 0.0245 ns and measured/floor 204,082x.",
      "ADMITTED COMPARATOR RESULT",
      "In the final protocol, canonical and broadcast16 aggregate medians tied; stage tile4 did not compile. The scalar comparison above remains explicitly historical and exploratory.",
      ...boundedClaim,
    ],
  },
  {
    lessonId: "gfx950-gpt-oss-120b-megakernel",
    evidencePath: `${evidence}; ${compatibility}; ${boundInputs}; examples/gfx950_gpt_oss_decode/ablation-variants-v1.json`,
    lines: [
      "OPTIMIZATION STACK AND CONTRIBUTION BREAKDOWN",
      "TIMING BOUNDARY: Every measured contribution below is historical evidence for the former single-Wave64/grid1 source. The current WG256/grid4 source has end-to-end correctness and ISA evidence, but no latency result.",
      "OPTIMIZATION [parallel-router]: Assign two of 128 logits per Wave64 lane and merge stable top-4 choices.",
      "IMPACT [parallel-router]: Measured serial 58.323676 ms -> optimized full kernel 1.065004 ms, a 54.7638x speedup and 98.1743% reduction.",
      "OPTIMIZATION [dispatch-fusion]: Fuse exact router, BF16 attention, MXFP4 expert projection, and disjoint stores.",
      "IMPACT [dispatch-fusion]: The da6 exact Rust component-materialization ablation measured component sum 1.251325 ms -> fused 1.065004 ms, a 1.17648x ratio and 14.8899% reduction.",
      "OPTIMIZATION [sequential-fragments]: Construct and consume each MXFP4 accumulator before the next.",
      "IMPACT [sequential-fragments]: Measured held 1.065404 ms -> sequential 1.065004 ms, a 0.0375% median reduction; VGPRs 352 -> 308 and AGPRs 96 -> 52.",
      "OPTIMIZATION [grouped-stores]: Commit three outputs as grouped disjoint stores.",
      "IMPACT [grouped-stores]: Aggregate medians favor grouped 1.065004 ms over interleaved 1.065524 ms, while paired ordering favors interleaving by 0.139%; unresolved, so grouped remains.",
      "OPTIMIZATION [bf16-lds-pipeline]: IMPLEMENTED; COMPILER-REJECTED. Prime, loop, and drain two 2,048 B LDS stages with prefetch distance one.",
      "IMPACT [bf16-lds-pipeline]: The current WG256/grid4 source is compiler-rejected because its retained pipeline scalar temporary has multiple definitions before the prime/loop/drain lifecycle can be admitted; no HSACO, numerical result, or timing is claimed.",
      "OPTIMIZATION [fp4-lds-pipeline]: UNAVAILABLE (NOT IMPLEMENTED). Apply the sealed pipeline to gfx950 FP4 fragments.",
      "IMPACT [fp4-lds-pipeline]: Unavailable in the admitted API; no source artifact was built or timed because the sealed pipeline element surface lacks an FP4 implementation.",
      "OPTIMIZATION [gpt-tile-tuning]: UNAVAILABLE (NOT IMPLEMENTED). Compare alternate BF16 and FP4 MFMA shapes.",
      "IMPACT [gpt-tile-tuning]: Unavailable in the admitted API; no source artifact was built or timed because only BF16 m16n16k16 and low-precision m16n16k128 Wave64 shapes are exposed.",
      "KERNEL: gfx950_gpt_oss_120b_decode_megakernel_v1",
      "CURRENT COMPATIBILITY WORKLOAD: 16 independent batch-1 items at WG256/grid4, four Wave64 items per workgroup; every item has a full 128-way top-4 router over hidden 2,880, a 16-token/16-column attention tile, and a selected top-1 MXFP4 expert K=128, N=16 tile.",
      "HISTORICAL PERFORMANCE WORKLOAD: one batch-1 Wave64 item at grid1; not a complete layer or model.",
      "SOFTWARE PIPELINE ASSESSMENT: Rejected for the implemented BF16 two-stage candidate; the fused dependency chain remains register-resident.",
      "LDS MULTI-BUFFER ASSESSMENT: Compiler-rejected for BF16 and unavailable for FP4 on the production-safe surface.",
      "TILE SHAPE ASSESSMENT: Current WG256/grid4 retained BF16 m16n16k16 plus MXFP4 m16n16k128 independently in each global wave; no alternate exact tile lowered.",
      ...protocol,
      "THEORETICAL RESOURCE FLOOR",
      "Historical single-item derivation: max(1,509,972 B / 8 TB/s, 745,472 FP32 ops / 144.2 TFLOP/s, 262,144 MXFP4 ops / 9.2 PFLOP/s) = 188.7465 ns; the historical 1.065004 ms single-wave result is 5,642.5x the floor. This ratio is not assigned to the current 16-item launch.",
      "ADMITTED COMPARATOR RESULT",
      "In the historical da6 single-wave campaign, the fused stack beats serial routing, held fragments, and the exact Rust component-materialization sum for that tile. Store ordering is unresolved. The current admitted WG256/grid4 variants have compatibility results only; no whole-model or universal SoTA claim is made.",
      ...boundedClaim,
    ],
  },
];

export const advancedPerformanceLessonIds = records.map(
  (record) => record.lessonId,
);

export function advancedPerformanceTabFor(
  lessonId: string,
): CodeTab | undefined {
  const record = records.find((candidate) => candidate.lessonId === lessonId);
  if (!record) return undefined;
  return {
    kind: "performance",
    label: "Performance",
    language: "text",
    code: [
      "FE2O3 GFX950 BOUNDED PERFORMANCE EVIDENCE",
      `Evidence source: ${record.evidencePath}`,
      "",
      ...record.lines,
    ].join("\n"),
    explanatory: true,
    notice:
      "Bounded MI350X ablation evidence. Comparator scope, protocol limits, correctness gates, and resource-floor assumptions are part of the record; no universal state-of-the-art claim is made.",
  };
}
