import { narrativeFingerprint } from "./narrative-fingerprint";
import { progressNarrativeFingerprints, progressNarrativeIds, type ProgressNarrativeId } from "./progress-narrative-policy";
import { deepFreeze, hasOwn } from "./registry";

const progressNarrativeRegistry = deepFreeze({
  "progress/last-audited-public-baseline": "This historical public baseline is newer than the lesson evidence pin. It is not presented as the current tip of either remote.",
  "progress/w0-host-link-closure-v1": "Accepted ancestor commit 9f40bbff39156f8b5f05868377ee12a2c4f74207, tree fd05530d3728aa928090b8e7beb372eaaf22b477, closes the bounded G1/W0 host-link prerequisite. Its dedicated genuinely static fe2o3-host-lld is built from pinned upstream LLVM/LLD archives; descriptor-sealed HostLinkClosureV1 inputs, exact-executable execveat launch, a receiver-owned sealed output, Landlock filesystem confinement, and seccomp denial of network and descriptor transfer bound the measured link slice. Two fresh guarded MI300X builds produced the same 85,597,472-byte tool with SHA-256 7c1a7429e93896393eb743ed54ead78ec6d492e3ed887183e67737b3872d7bf9; the registered secure-protocol CTest and a separate real HostLinkClosureV1 link slice passed. This is measured/no-authority evidence only. W0 grants no protected publication, broker or durable artifact handoff, runtime, load, launch, or GPU authority or evidence; it proves neither memory safety nor race freedom and establishes no source-to-machine or Verus-to-machine refinement. It promotes no cuda-oxide parity or tutorial evidence row.",
  "progress/broker-v4-inert-foundation": "Public commit 66393d3ca7a6805633ed94e12c707a6d22bdf1ad, tree f39f9c76d964bafe9e8a12a0b48099766490b366, adds the inert Broker V4 capability binding, canonical prepare/grant/commit frames, transcript validation, and the BrokerReplayRegistryV4 integration seam while preserving Broker V3. Every V4 binding, frame, validator, claim, and completed transcript reports AUTHORITY=none. Copyable inputs and public validator construction permit equivalent transcripts to be validated again, so this layer establishes neither freshness nor global or crash-persistent replay exclusion and grants no execution or publication authority. No registry implementation, default registry, always-allow fallback, or runtime-owned session capability is provided. W1 remains the next production blocker: a broker-owned durable registry must atomically reserve a unique session before host linking, issue an unforgeable move-only capability, bind completion to the exact reservation and transcript, persist replay exclusion across restart, and consume the capability exactly once at durable publication. This public protocol foundation promotes no cuda-oxide parity or tutorial evidence row.",
  "progress/w0b-host-link-rejection": "Candidate commit 2e5ad53bcb20f2a46e91128a42e838d918d61581, tree 892f014381cd3e34f81cb05df3b9bbda4a412478, is rejected and is not integrated, accepted, or public. On MI300X it crossed the static binding-wrapper, Cargo, rustc, backend, and kernel-collection boundaries, then failed closed because the broker lacked an authenticated cargo-fe2o3 executable identity. It executed zero Workers and reached no artifact admission, load, dispatch, or GPU result; it opened no COMGR path. Independent code review also found that its dynamically linked host rust-lld subprocess left the ELF loader and system DSOs, CRTs, archives and objects, search roots, and forwarded Cargo target artifacts outside the authenticated closure. env_clear reduces ambient configuration but does not authenticate those dependencies. W0 is a dedicated, genuinely static fe2o3-host-lld built from pinned upstream LLVM/LLD archives plus a descriptor-backed HostLinkClosureV1, with pre-link and post-link closure revalidation. W1 is authenticated broker cargo-fe2o3 executable identity and follows W0. Retaining dynamic rust-lld is rejected, while an in-process host LLD is deferred. Device code-object linking remains pinned upstream LLVM target-machine APIs plus in-process LLD, with no COMGR or shell GPU linker. This rejection and design decision promote no parity or evidence row.",
  "progress/production-s09-rustc-invocation": "The production path canonically captures RustcInvocationDescriptorV2 and admits exactly /proc/./self/fd/198 as its backend capability. It rejects procfs/devfd aliases, other descriptor numbers, every preexisting joined or split codegen-backend selector spelling, and an option terminator before the sole final managed -Zcodegen-backend=<path> selector. A real cargo-fe2o3 integration test traverses pinned Cargo, the S09 broker, closed-environment materialization, pinned rustc spawn, Worker V2, and durable publication of a COV6 gfx942:xnack- HSACO containing exactly alpha. It decodes the canonical publication envelope and nested record, then binds the finalized-output identity and content-addressed artifact name to the exact inspected HSACO bytes. A retained mi300x observation records 1 passed in 132.45 seconds and HSACO SHA-256 5902632c5c249be05855ae5cef62bb9096a1f9277cfb0c58b4384594d6ee61de. This is non-authoritative: it proves no compiler origin and grants no loading, execution, or verification authority. Canonical cwd pathname capture is not a pathname-to-object identity join, and the scalar profile still establishes no general source or output-object association.",
  "progress/authenticated-verus-v2": "Linux x86_64 authenticated execution is bound to pinned local runtime and tool snapshots. V2 uses clone3 pidfds and ptrace-unresumable checkpoints, seccomp process-creation denial, exact live executable/backing comparison, runtime closure and baseline pinning, vDSO pinning, and immutable sealed results. It rejects compressed and alternate debug-section families. Package-scoped debug stripping makes the debug fixture reproducible, and a bounded two-root gate compares SHA-256, size, and Build ID. On the pinned local host, debug V2 integration passed 14/14 and release passed 13/13; the full verifier debug and release suites and 22 doctests passed. A run on mi300x correctly failed closed on its different vDSO and runtime baseline. This does not integrate stock Verus or Z3, establish semantic proof validity, guarantee exclusive measured-image execution between checkpoints, prove compiler refinement, or grant GPU authority.",
  "progress/cargo-acknowledgement-repair": "V6 passed 100/100 contention, 10/10 finalizer, 280/280 vertical, release, focused, and fresh mi300x generic gates without changing production timeouts. Both public mains are exact, and both hosted policy and generic workflows are green.",
  "progress/formal-evidence-isolation-v11": "V12 prototypes an Ed25519-signed external authority handoff, but protected evidence remains rejected. Independent policy anchors, separately sealed statement transport, hostile substitution and replay probes, and the full regression and reproducibility matrix are still required.",
  "progress/protected-evidence-publisher": "V11 uses three independently checksummed checkpoints to bind the committed prefix and allows recovery only beyond it. Independent hostile rereview and the replayed full mi300x generic suite passed; both public main branches now contain the accepted merge.",
  "progress/gfx942-scalar-control-flow": "Independent hostile review rejected V4: preload constructors run before authority, clone can create namespaces, preload nondumpability is bypassable, fake rustc stderr can satisfy admission, and the authenticated build closure is incomplete. V5 must close all five attacks.",
  "progress/collected-rust-scalar-admission": "V4 preserves admission-only and no-HSACO scope, but its compiler and process authority can be forged or escaped. V5 is adding pinned positive backend identity, complete closure authentication, and adversarial process-boundary tests before any executable claim.",
  "progress/gfx942-wave64-lds-reduction": "Both public mains contain ordinary attributed Phase A source, checked CPU oracles, deterministic mutations, and a Verus model for the exact masked Wave64 reduction and scans. A source-derived compiler profile binds exact attributed source, FnAbi, trusted definitions, complete reachable portable MIR, gfx942:xnack-/COV6/Wave64 geometry, mask semantics, ordered collectives, and lane-owned outputs to a closed semantic Kernel IR sidecar. The exact finalizer uses in-process upstream LLVM target emission and LLD library APIs, never COMGR or shell tools, and checks post-link target metadata, ABI resources, relocations, dependencies, unresolved symbols, and machine calls. A typed one-shot HSA lifecycle completed one protected gfx942 observation over four exact masks with canaries, unchanged inputs, exact-bit outputs, and terminal unload. This remains bounded observation evidence, not compiler or Verus-to-machine refinement. The separate synchronization source now has a checkout-relocatable exact compiler profile; direct LLVM/LLD finalization and runtime evidence remain in progress.",
  "progress/workgroup-sync-direct-finalization": "Commit 3d673ffb9a962d7c4b8ae7526bbe881260e19c72 publishes exact gfx942:xnack-/COV6 upstream LLVM target-machine and in-process LLD finalization for the fixed WG64 LDS reduction and system-scope relaxed atomic profiles. Closed checks cover target, symbols, source/KIR/profile identity, dynamic LDS metadata, barrier and atomic effects, ABI resources, relocations, dependencies, unresolved calls, opcodes, machine image, and reproducibility. The admitted HSACO receipt is opaque and byte-inaccessible. Primary combined-tree debug and release finalizer suites each passed 55 tests with 4 configured-worker tests ignored; scoped clippy and formatting passed. This authenticates neither compiler origin nor source, compiler, or machine refinement; it grants no publication, load, dispatch, launch, numerical, race-freedom, or hardware authority. Typed host/runtime dispatch and protected gfx942 evidence remain open.",
  "progress/workgroup-sync-host-runtime": "Commit 51751e48812d6428627b8d403be72d24558175b5 adds exact typed host and HSA runtime mechanics for the fixed WG64 LDS-reduction and system-scope relaxed-atomic profiles. Typed arguments bind extents, allocation provenance and identity, alignment, access roles, alias exclusions, exact COV6 ABI and resources, profile identity, and context/device/runtime continuity. Private non-Clone states consume one Joined -> Loaded -> Completed -> Unloaded lifecycle, bind 256 bytes of dynamic LDS at hidden offset 160 and in the AQL group segment, and allow one terminal unload. Eleven compile-fail pairs reject safe finalized-byte access, cloning, aliasing, cross-profile use, early or repeated unload, raw kernargs, native handles, and private ABI construction. Combined debug and release host suites each passed 313 unit tests with 5 ignored plus the full UI and doctest matrix; runtime suites each passed 32 unit tests plus authority UI and harness checks; scoped Clippy, formatting, and diff checks passed. The protected tests fail closed without measured worker pins. On MI300X the real worker currently stops before HSA load because its LLVM module data layout does not match the target machine. Therefore this checkpoint grants typed lifecycle and dispatch-binding mechanics only: no successful GPU launch, numerical result, compiler origin, source/compiler/machine refinement, generalized memory safety, or race-freedom authority is claimed.",
  "progress/workgroup-sync-protected-hardware": "Commit 4138e034b7ee9f457d9b63b4d54bdc623d0c8046 closes the exact workgroup-sync data-layout blocker without an exception. Both Rust handoffs use one canonical gfx942 layout string, carry its SHA-256 identity, and the upstream LLVM 22 worker derives the authoritative value through TargetMachine::createDataLayout(). Exact profiles require literal canonical equality and reject missing, host, stale, near-match, reordered, G1-to-G2, identity, and provider substitutions. Debug and release workers produced identical raw and finalized outputs. Primary combined-tree validation passed full debug/release finalizer suites, strict Clippy and formatting, and debug/release C++ codec, pipeline, and device-library-policy tests. Through the normal measured-worker pins and private typed lifecycle on MI300X, both the exact WG64 dynamic-LDS reduction and system-scope relaxed atomic kernel passed in debug and release with canaries, unchanged inputs, exact CPU oracles, bounded completion, and terminal unload. This is exact-profile protected hardware observation only. It does not establish compiler origin, source-to-Kernel-IR, Kernel-IR-to-LLVM/ISA or Verus-to-machine refinement, IEEE generality, generalized illegal-access safety, or generalized race freedom.",
  "progress/row-softmax-release-checkpoint": "Historical commit aca28306fe89c036dc0129349ef9ed685a43c7bb, tree 37f1a92e0be0a4b48c5cef1b1a48327e0ea4c828, records the earlier G3 exact fixed 64-element row-softmax 25-pin checkpoint. It binds attributed Rust source, the exact gfx942:xnack-/COV6/WG64 compiler descriptor, the single-use Worker V2 handoff, the pinned OCML import closure, deterministic finalization, typed host and linear HSA lifecycle mechanics, and a staged receipt covering all 25 release pins. Hostile tests reject argv, environment, loader, descriptor, provider, source, profile, target, replay, and file-descriptor substitutions. MI300X validation ran the target-isolated backend library and all 19 integration targets, including the 18-test clean external handoff suite, plus exact release blocker tests, strict Clippy, formatting, parity gates, UI/doctest checks, and S09 guards. At that historical checkpoint production failed closed before GPU launch at the then-unresolved host-link boundary; the debug-only validation route was explicitly non-authoritative. The current closure sequence is W0 authenticated HostLinkClosureV1, then W1 broker cargo-fe2o3 executable identity. This historical checkpoint remains distinct from the later LLVM release pair and claims no production hardware result, source or Verus-to-machine refinement, generalized illegal-access safety, or generalized race freedom.",
  "progress/row-softmax-llvm-release": "The row-softmax LLVM release pair is implementation commit A 31bf96a21c0a2bbfb55c44f9a22b7350cabcfcb1, tree 293c6d39e47d64f5949d450d6041dc598aafd0fe, followed by manifest commit B fd89390788adc5670c54ecc2517b9720f2f80113, tree af0156687517c0e71eb0d607917964b7c375af43. B pins tools/fe2o3-llvm-link-worker/row-softmax-v1-release-manifest.txt with SHA-256 9c7dc4a08f2f972b581ffa0f88bf8834d2098f21ff57b1a8594dd4dfca03759c. Two fresh complete MI300X runs passed; independent review accepted the evidence package. The runs reproduced the retained worker, probe, runtime closure, upstream LLVM closure, Cargo vendor closure, Rust sysroot closure, and the single retained HSACO identity 0864047320a7ade5eba29d3fbb3ef9efefcf2a1378097061010d163af461db93. The GPU code-object path remains pinned upstream LLVM target-machine APIs plus in-process LLD. The runs did not dispatch a GPU and establish only bounded compiler/code-object reproducibility and operator-selected reviewed integrity. They grant no runtime or GPU result, authentication, source/model/Verus-to-machine refinement, generalized memory-safety, illegal-access, or race-freedom authority.",
  "progress/flash-attention-compiler-admission": "Commit bfc32b51314e75e4d619eda244e0d78573f1232c completes exact compiler admission for the fixed B=1, H=1, N=8, D=16 causal FlashAttention source. The closed profile binds ordinary attributed source, namespace, wrapper, FnAbi, compiler configuration, complete reachable portable MIR, a semantic Kernel IR sidecar, and V3 provider identity. Hostile tests reject source, ABI, compiler-profile, MIR, Kernel IR, and provider substitutions, and focused debug and release integration each passed all three tests. The relocatable identity binds stable crate and definition identity, Cargo source closure, relative paths, and source bytes; the device-crate hash is same-session evidence only. No artifact, LLVM finalizer, HSA runtime, GPU execution, exponential-law, IEEE FP32/OCML, numerical, performance, or source/model-to-machine authority is claimed.",
  "progress/flash-attention-direct-finalization": "Commit 0b8ddf138d5420b90a61463ade8d612eb7101090, tree 2799167a3fdc0a31666843bb6d8cbffde89bf38f, publishes G4 structural finalization for the exact B=1, H=1, N=8, D=16 causal FlashAttention profile. The authenticated compiler inputs enter a single-use Worker V2 handoff; the configured worker uses upstream LLVM target-machine APIs and in-process LLD, checks the pinned OCML provider closure and exact gfx942:xnack-/COV6 profile, and produces deterministic raw and finalized output identities. The resulting non-Clone receipt is opaque: safe code cannot access its bytes, replay it, or convert it into publication, load, or launch authority. Hostile tests reject handoff, module, descriptor, provider, machine, output, replay, and safe-API substitutions. This is compiler-handoff, finalizer, and opaque deterministic-receipt evidence only. It grants no publication, load, launch, runtime, GPU, numerical, performance, compiler-refinement, OCML-semantics, general memory-safety, or race-freedom authority. The receipt reports no measured proof of no-COMGR linkage; an independently measured worker manifest would be required for that separate claim.",
  "progress/flash-attention-upstream-reproducibility": "Commit c1aecbb11017125e84209a333d978ec6d5bdddb1, tree 25e9d46354bccb96550ee8dac4da4c6b2e7bd45f, makes pinned upstream LLVM 22.1.8 plus in-process LLD the sole exact FlashAttention V1 machine compiler identity. Two previously absent worker build directories and two absent Cargo and evidence directory pairs on MI300X produced byte-identical workers, handoffs, textual IR, linked and optimized bitcode, objects, raw HSACO, transcripts, and extracted kernel bodies. The canonical gfx942:xnack- COV6 kernel-body SHA-256 is d2aa57c0f468f574f44a9fea06bbb8e98aa9b60bb2d9303cc4d8b6caf0cfca54 over 2540 bytes. ROCm LLVM 7.2.4 is rejected before TargetMachine construction, and its former 60e092 result remains forensic drift only; the first measured toolchain divergence is linked bitcode. The combined tree passed the real upstream finalizer, focused upstream and ROCm identity tests, the full finalizer test suite, MoE cross-profile finalization, strict lint, docs, formatting, and diff checks. The GPU device code-object path introduced no COMGR or shell GPU linker. This establishes same-host reproducible machine bytes for one closed profile and one pinned upstream LLVM installation only. It establishes no functional Flash semantics, protected GPU result, numerical accuracy, memory safety, race freedom, performance, independently rebuilt LLVM reproducibility, or compiler or LLVM-to-ISA refinement.",
  "progress/flash-attention-typed-runtime": "Commit 26c80737e3380cd73df21d9a8abd1838cdfa76bc, tree 7c25b5807addeaaab26036a78fc414ea4803dc2c, publishes host and runtime mechanics for the exact B=1, H=1, N=8, D=16 causal FlashAttention profile. Its typed four-buffer binding retains shared read-only query, key, and value leases plus one unique write-only output lease; exact region validation rejects output/input aliasing. A private non-Clone Joined -> Loaded -> Completed -> Unloaded lifecycle consumes the receipt, load, dispatch/wait, and unload transitions linearly, while the reviewed production HSA adapter observes the retained executable, kernel, group-segment, and private-segment resources. Nine compile-fail cases reject receipt replay or cloning, lifecycle cloning, raw native objects, raw kernargs, safe receipt-byte access, cross-profile substitution, output/input aliasing, early unload, and repeated unload. An independent strict-f32 CPU oracle covers nominal, equal-score, dominant-score, causal-mask, exceptional-input, unchanged-input, and guard-canary cases. The ignored protected MI300X test fails closed before HSA load pending W0 authenticated HostLinkClosureV1, W1 broker cargo-fe2o3 executable identity, and subsequent opaque linear receipt injection; it refuses artifact-path and raw-byte fallbacks. This checkpoint is host/runtime mechanics, reviewed resource-observation, compile-fail boundary, and independent-oracle evidence only. It claims no protected GPU dispatch or numerical GPU result, compiler or OCML semantics, source/model/Verus-to-machine refinement, general memory safety, or race freedom.",
  "progress/flash-attention-memory-proof": "Commit 182d5673327bdbf642e3328a50903a4607a1756c, tree c45ae5ac9f085e29fd1a2356ca82a6c8ac0f4749, adds an exact B=1, H=1, N=8, D=16 logical memory/effect checker and a separate pinned Verus source. The fixed source model covers 64 lanes, 128 f32 elements per tensor, causal query/key/value reads, 512-byte admitted regions, two output slots per lane, output ownership, disjoint writes, and read-before-commit ordering. Verus reports 13 verified obligations and the fail-closed runner rejects all eight pinned mutations of lane mapping, extent, address space, access width, effect order, effect identity, published machine-body expectation, and analyzer-profile expectation. The Rust expected-evidence descriptor is copyable and explicitly inert; it authenticates nothing, cannot manufacture a proof receipt, and leaves has_identity_bound_verus_receipt false. No AuthenticatedVerusExecutionReceiptV2 join, compiler or Kernel-IR refinement, LLVM/ISA or logical-address refinement, final-artifact binding, machine memory-safety claim, generalized race-freedom claim, publication/load/launch authority, or GPU execution result is present.",
  "progress/moe-top2-compiler-admission": "Commit 40e04f8e8469f37d3e9c4fcfcb23bd5ab6d1536e completes exact compiler admission for fixed T=8, E=4, K=2, C=4 deterministic MoE top-2 routing. The closed profile binds ordinary attributed source, namespace, wrapper, FnAbi, compiler semantics, complete reachable portable MIR, V3 provider identity, target/COV6/WG64 ABI and resources, and a semantic Kernel IR sidecar covering lower-expert tie breaking, counts, capacity, exclusive scans, stable dropping, unique slots, permutation and inverse maps, and sentinel tails. Primary full KIR and backend suites passed in debug and release; focused external-project admission passed 3/3 in both profiles, and two independent MI300X checkout paths produced identical authority. This private single-use receipt grants no generic or LLVM lowering, artifact, finalizer, runtime, GPU, IEEE FP32, Verus-refinement, numerical, performance, or source/model-to-machine authority.",
  "progress/moe-top2-direct-finalization": "Commit 8926b3f725a9cb6a15bc8f43f019af1afffc6c1c, tree edad7563491b8f892696014ae071ddc116a7d2d0, publishes G5 structural finalization for the exact T=8, E=4, K=2, C=4 deterministic MoE top-2 routing profile. The authenticated compiler handoff binds the attributed source, complete reachable portable MIR, semantic Kernel IR, descriptor, target, ABI, resources, and provider identity into a single-use Worker V2 exchange. The worker uses upstream LLVM target-machine APIs and in-process LLD, then checks the exact gfx942:xnack-/COV6 structural ELF, machine, metadata, descriptor, and resource profile. Its non-Clone receipt is opaque, deterministic, and identity-only. The measured direct worker passed in debug and release with identical raw and finalized output identities; focused compiler, finalizer ownership, compile-fail boundary, shared worker-pipeline, formatting, lint, dashboard, and parity checks also passed. The GPU device code-object path exposes no COMGR or shell GPU linker, but this is not measured no-COMGR authority because no measured worker manifest establishes that separate property. This checkpoint is authenticated compiler-handoff, exact structural worker/finalizer, opaque deterministic-receipt, and bounded measured-worker evidence only. It grants no publication, load, launch, runtime, GPU numerical, performance, compiler-refinement, Verus-to-machine, general memory-safety, or race-freedom authority.",
  "progress/moe-top2-typed-runtime": "Commit b1302940e9f7bc1cdcd58709a5d716bc2404df97, tree 6de71f0b421607862f0c57a761d8f2018e6bc090, publishes exact typed host/runtime mechanics for the fixed gfx942:xnack- T=8, E=4, K=2, C=4 routing-only MoE profile. The eight-buffer binding retains logits as shared read-only and seven output regions as unique read-write leases, enforces exact extents, target and context identity, pairwise disjointness, and the 128-byte explicit and 384-byte complete kernarg ABI, and exposes no public raw addresses or kernarg bytes. A private non-Clone Joined -> Loaded -> Completed -> Unloaded lifecycle validates environment, load, symbol, resources, hidden kernarg initialization, quiescent dispatch, and terminal unload observations. Five binder tests, five lifecycle tests, nine compile-fail cases, finalizer opacity checks, Flash cross-profile gates, strict lint and formatting, and parity consistency passed on MI300X. An independent CPU oracle covers lower-expert ties, stable capacity drops, exclusive offsets, permutation and inverse relations, sentinel tails, exceptional logits, unchanged inputs, and canaries. The protected test remains ignored and fails closed before HSA load pending W0 authenticated HostLinkClosureV1, W1 broker cargo-fe2o3 executable identity, and subsequent opaque linear receipt injection. This is typed ownership, lifecycle, observation, compile-fail, and CPU-oracle evidence only. It establishes no protected GPU routing result, hardware routing semantics, compiler or LLVM/ISA refinement, generalized memory safety or race freedom, expert GEMM, combine, end-to-end MoE output, or performance claim.",
  "progress/moe-top2-memory-proof": "Commit d9ee4d09a97e59982b5e9ccf2e3877fff84fab5b, tree 08141f73c1ed8f7ca99ac852b23e49989089dd76, adds an exact fixed T8/E4/K2/C4 logical memory/effect checker and a separate pinned Verus source. The model covers the eight exact buffers, byte extents, pairwise region disjointness, lane-zero output ownership, unique logical write owners, stable routing-phase order, and bounded expert, route, slot, permutation, and inverse values including the drop sentinel. Verus reports 16 verified obligations and the fail-closed runner rejects all eight pinned mutations at their named postconditions. The runner pins the kernel, proof, Verus executable, complete release closure, negative sources, and transcript. Primary MI300X validation passed 10 checker tests, 38 canonical example tests, the exact proof run, strict Clippy, formatting, and diff checks. The copyable expected-evidence descriptor is explicitly inert and cannot mint or join an authenticated Verus receipt. This remains a fixed logical-source model: it establishes no source/compiler/KIR/LLVM/ISA or logical-address refinement, artifact authority, generalized machine memory safety or race freedom, protected GPU execution, or numerical GPU result.",
  "progress/moe-expert-bounded-evidence": "Public tip 66393d3ca7a6805633ed94e12c707a6d22bdf1ad, tree f39f9c76d964bafe9e8a12a0b48099766490b366, retains the bounded MoE V2 proof and host-bridge evidence originally integrated at commit 2042382cb07283c4339c05c6372c6798bd5ceb7b, tree e4a964c61dd43e1ac5e54adc2562f6e77f2e6654. For exactly E4/C4/routes16/width16/tile256, the inert compact-plan model proves bounded source and destination ranges, pairwise disjoint ordered destinations, an exact accepted-prefix union, and a defined zero tail; Verus reports 19 verified obligations, all seven expected-failure mutations are rejected, and the Rust checker exhaustively covers all 625 count vectors. The host bridge checks internal consistency of caller-supplied top2 experts, requested and admitted counts, offsets, route slots, permutation, and inverse, then synchronously uploads offsets and inverse together and retains both immutable device regions. The gfx942 upload/readback test is no kernel dispatch. Integration and publication gating change availability, not authority: this evidence does not authenticate router execution or device readback provenance, prove top2 selection from logits, bind route weights or packed activations, or grant freshness, replay, compiler, finalizer, artifact, load, or dispatch authority. It establishes no router or expert GPU execution, generalized source-to-machine refinement, numerical or performance result, memory-safety authority, or race-freedom authority. The MoE expert row therefore remains Partial.",
  "progress/scalar-gemm-v1": "Both public mains contain the source-bound frontend handoff (SHA-256 2569dcdc19df8d64fb937e65bb64737c6c2a3c5e68ad6adc5dee86df373e6cb5), measured upstream LLVM/LLD Worker, deterministic canonical finalization, retained-currentness load handoff, proof and physical-effect profiles, and a raw MI300X smoke test. The frontend commitment records lineage; it does not yet authenticate source-to-module causality. The 10,128-byte gfx942:xnack- COV6 artifact (SHA-256 ac1da70c69a5038b887b459dece40802668c41bcf98f621d7d1273d2f61ba2c9) passed every HARDWARE_CASES case in 1.41 seconds, including zero-output no-dispatch, k=0 +0, bitwise CPU-oracle, immutable-input, adjacent-canary, and unload checks. The raw smoke deliberately bypasses production prerequisite authentication. The upstream LLVM 22 MC analyzer now accepts those exact artifact bytes without COMGR: 4/4 native tests passed on mi300x for the exact 60-opcode scalar profile, one function, zero calls, two constrained backward loops, and 19 ordered physical effect sites. Both the analyzer result and raw smoke remain static or observational evidence and grant no protected authority. Authenticated Verus execution, analyzer-identity binding, compiler and address refinement, memory, bounds and race proofs, and production protected launch evidence remain open.",
  "progress/scalar-gemm-proof-profile": "Nine focused tests pin the exact 6,879-byte proof source (SHA-256 98803a62488e1af2fbc886b1da5ddc680b16d35a8a8a5c22d4959128dd2da5fe) and bind its target, ABI, effects, launch contract, seven required properties, tool identities, transcript, caller-supplied freshness, and finalized artifact digest. Replay is explicitly permitted after the process-local ledger is recreated. This is inert review evidence only: it does not execute Verus and creates no load, launch, or protected-evidence authority.",
  "progress/scalar-gemm-physical-effects": "On mi300x, 4/4 upstream LLVM 22 MC analyzer tests accepted the exact finalized artifact (SHA-256 ac1da70c69a5038b887b459dece40802668c41bcf98f621d7d1273d2f61ba2c9) without COMGR. The exact 60-opcode scalar profile has one function, zero calls, two constrained backward loops, and effects of 9 address / 8 read / 1 write / 1 return / 0 calls. The Rust profile now also binds the exact entry range [0x1b00, 0x25d0) and all 19 ordered physical effect sites, including address/access pairing; focused mutation tests reject relocation, reordering, width, range, and pairing changes. This is static, inert evidence only. It provides no compiler or address refinement and no proof of memory safety, bounds safety, race freedom, or launch correctness. The analyzer identity changed and downstream authenticated evidence must bind the new identity.",
  "progress/tiled-gemm-layout-frontend": "The standalone gfx942:xnack- BF16/F32 host scaffold and source-level layout proof begin at commit 027ab901bef7007d0e8da3370470556ed28baad1. Executable Rust maps bind the official A/B/C/D register coordinates for gfx942 V_MFMA_F32_16X16X16_BF16 to AMD Matrix Instruction Calculator commit 2ef91896bcdc4d26624f952e5c905c787cd9bc9e, with XOR4 LDS staging for A and deliberately transposed B. Exhaustive 64-lane x 4-component goldens pin all four tables; 23 public Verus proof functions discharge 73 obligations; and five formula mutations are rejected. Descendants separate block counts, WG64 dimensions, and AQL work items, then add a sealed direct-global one-wave 16x16x16 Kernel IR graph with 12 reads, one BF16/BF16/F32 MFMA, and four F32 stores. Frontend checkpoint 286331aab8639dd3707e55cdf51a83f8854d26a5 separately records a build-scoped WG64/288-byte fragment probe. It is neither the later four-slice production profile nor the independent WG256/384-byte mutation, and it does not establish source-to-canonical Kernel IR correspondence."
} satisfies Record<ProgressNarrativeId, string>);

export const SAFE_PROGRESS_DETAIL = "Checkpoint detail unavailable because its policy binding is invalid.";

export function isProgressNarrativeId(value: unknown): value is ProgressNarrativeId {
  return typeof value === "string" && hasOwn(progressNarrativeRegistry, value);
}

export function resolveProgressNarrative(value: unknown): string | undefined {
  if (!isProgressNarrativeId(value)) return undefined;
  const detail = progressNarrativeRegistry[value];
  return narrativeFingerprint(detail) === progressNarrativeFingerprints[value]
    ? detail
    : undefined;
}

export function validateProgressNarrativeRegistry(
  candidate: Record<string, unknown> = progressNarrativeRegistry,
): string[] {
  const issues: string[] = [];
  const actualIds = Object.keys(candidate);
  if (actualIds.length !== progressNarrativeIds.length || actualIds.some((id, index) => id !== progressNarrativeIds[index])) {
    issues.push("registry does not contain the exact progress narrative ID order");
  }
  for (const id of progressNarrativeIds) {
    if (!hasOwn(candidate, id)) {
      issues.push(`${id}: missing canonical progress narrative`);
      continue;
    }
    if (narrativeFingerprint(candidate[id]) !== progressNarrativeFingerprints[id]) {
      issues.push(`${id}: canonical progress narrative text drift`);
    }
  }
  return issues;
}

export function progressNarrativeRegistrySnapshot(): Record<string, string> {
  return structuredClone(progressNarrativeRegistry) as Record<string, string>;
}

export { progressNarrativeIds };
